patterns = {
    "ace05-en": {
        "Business:Declare-Bankruptcy": ["Org"], 
        "Business:End-Org": ["Org", "Place"], 
        "Business:Merge-Org": ["Org"], 
        "Business:Start-Org": ["Agent", "Org", "Place"], 
        "Conflict:Attack": ["Attacker", "Target", "Instrument", "Place", "Agent"], 
        "Conflict:Demonstrate": ["Entity", "Place"], 
        "Contact:Meet": ["Entity", "Place"], 
        "Contact:Phone-Write": ["Entity", "Place"], 
        "Justice:Acquit": ["Defendant", "Adjudicator"], 
        "Justice:Appeal": ["Plaintiff", "Place", "Adjudicator"], 
        "Justice:Arrest-Jail": ["Person", "Agent", "Place"], 
        "Justice:Charge-Indict": ["Defendant", "Prosecutor", "Place", "Adjudicator"], 
        "Justice:Convict": ["Defendant", "Place", "Adjudicator"], 
        "Justice:Execute": ["Person", "Agent", "Place"], 
        "Justice:Extradite": ["Person", "Destination", "Origin", "Agent"], 
        "Justice:Fine": ["Entity", "Place", "Adjudicator"], 
        "Justice:Pardon": ["Defendant", "Adjudicator"], 
        "Justice:Release-Parole": ["Person", "Entity", "Place"], 
        "Justice:Sentence": ["Defendant", "Place", "Adjudicator"], 
        "Justice:Sue": ["Defendant", "Plaintiff", "Place", "Adjudicator"], 
        "Justice:Trial-Hearing": ["Defendant", "Prosecutor", "Place", "Adjudicator"], 
        "Life:Be-Born": ["Person", "Place"], 
        "Life:Die": ["Agent", "Victim", "Instrument", "Place"], 
        "Life:Divorce": ["Person", "Place"], 
        "Life:Injure": ["Agent", "Victim", "Instrument", "Place"], 
        "Life:Marry": ["Person", "Place"], 
        "Movement:Transport": ["Artifact",  "Destination", "Origin", "Vehicle", "Agent", "Place"], 
        "Personnel:Elect": ["Person", "Entity", "Place"], 
        "Personnel:End-Position": ["Person", "Entity", "Place"], 
        "Personnel:Nominate": ["Person", "Agent"], 
        "Personnel:Start-Position": ["Person", "Entity", "Place"], 
        "Transaction:Transfer-Money": ["Giver", "Recipient", "Place", "Beneficiary"], 
        "Transaction:Transfer-Ownership": ["Buyer", "Artifact", "Seller", "Place", "Beneficiary"], 
    }, 
    "richere-en": {
        "Business:Start-Org": ["Agent", "Org", "Place"], 
        "Business:Merge-Org": ["Org"], 
        "Business:End-Org": ["Org", "Place"], 
        "Business:Declare-Bankruptcy": ["Org"], 
        "Conflict:Attack": ["Attacker", "Target", "Instrument", "Place", "Agent"], 
        "Conflict:Demonstrate": ["Entity", "Place"], 
        "Contact:Meet": ["Entity", "Place"], 
        "Contact:Correspondence": ["Entity", "Place"], 
        "Contact:Broadcast": ["Entity", "Audience", "Place"], 
        "Contact:Contact": ["Entity", "Place"], 
        "Justice:Arrest-Jail": ["Person", "Agent", "Place"], 
        "Justice:Release-Parole": ["Person", "Agent", "Place"], 
        "Justice:Trial-Hearing": ["Defendant", "Prosecutor", "Place", "Adjudicator"], 
        "Justice:Charge-Indict": ["Defendant", "Prosecutor", "Place", "Adjudicator"], 
        "Justice:Sue": ["Defendant", "Plaintiff", "Place", "Adjudicator"], 
        "Justice:Convict": ["Defendant", "Place", "Adjudicator"], 
        "Justice:Appeal": ["Defendant", "Place", "Adjudicator", "Prosecutor"], 
        "Justice:Sentence": ["Defendant", "Place", "Adjudicator"], 
        "Justice:Fine": ["Entity", "Place", "Adjudicator"], 
        "Justice:Execute": ["Person", "Agent", "Place"], 
        "Justice:Extradite": ["Person", "Destination", "Origin", "Agent"], 
        "Justice:Acquit": ["Defendant", "Adjudicator", "Place"], 
        "Justice:Pardon": ["Defendant", "Adjudicator", "Place"], 
        "Life:Be-Born": ["Person", "Place"], 
        "Life:Marry": ["Person", "Place"], 
        "Life:Divorce": ["Person", "Place"], 
        "Life:Injure": ["Agent", "Victim", "Instrument", "Place"], 
        "Life:Die": ["Agent", "Victim", "Instrument", "Place"], 
        "Movement:Transport-Person": ["Person", "Destination", "Origin", "Instrument", "Agent"], 
        "Movement:Transport-Artifact": ["Artifact", "Destination", "Origin", "Agent"], 
        "Manufacture:Artifact": ["Artifact", "Agent", "Place"], 
        "Personnel:Start-Position": ["Person", "Entity", "Place"], 
        "Personnel:End-Position": ["Person", "Entity", "Place"], 
        "Personnel:Nominate": ["Person", "Agent", "Place"], 
        "Personnel:Elect": ["Person", "Agent", "Place"], 
        "Transaction:Transfer-Ownership": ["Thing", "Giver", "Recipient", "Place", "Beneficiary"], 
        "Transaction:Transfer-Money": ["Giver", "Recipient", "Place", "Beneficiary"], 
        "Transaction:Transaction": ["Giver", "Recipient", "Place", "Beneficiary"], 
    },
    "m2e2": {
        "Conflict:Attack": ["Attacker", "Target", "Instrument", "Place"], 
        "Conflict:Demonstrate": ["Entity", "Place", "Police"], 
        "Contact:Meet": ["Entity", "Place"], 
        "Contact:Phone-Write": ["Entity", "Place"],         
        "Justice:Arrest-Jail": ["Person", "Agent", "Place"],
        "Life:Die": ["Agent", "Victim", "Instrument", "Place"], 
        "Movement:Transport": ["Artifact",  "Destination", "Origin", "Vehicle", "Agent"], 
        "Transaction:Transfer-Money": ["Giver", "Recipient"], 
    }, 
    "geneva": {
        "Achieve": ["Agent", "Goal", "Means"],
        "Action": ["Act", "Agent", "Domain", "Manner"],
        "Adducing": ["Medium", "Role", "Speaker", "Specified_entity"],
        "Agree_or_refuse_to_act": ["Proposed_action", "Speaker"],
        "Arranging": ["Agent", "Configuration", "Location", "Theme"],
        "Arrest": ["Authorities", "Charges", "Offense", "Suspect"],
        "Arriving": ["Goal", "Means", "Path", "Place", "Purpose", "Source", "Theme"],
        "Assistance": ["Benefited_party", "Focal_entity", "Goal", "Helper", "Means"],
        "Attack": ["Assailant", "Means", "Victim", "Weapon"],
        "Bearing_arms": ["Protagonist", "Weapon"],
        "Becoming": ["Entity", "Final_category", "Final_quality"],
        "Becoming_a_member": ["Group", "New_member"],
        "Bodily_harm": ["Agent", "Body_part", "Cause", "Instrument", "Victim"],
        "Bringing": ["Agent", "Area", "Carrier", "Goal", "Source", "Theme"],
        "Building": ["Agent", "Components", "Created_entity", "Place"],
        "Catastrophe": ["Cause", "Patient", "Place", "Undesirable_event"],
        "Causation": ["Actor", "Affected", "Cause", "Effect", "Means"],
        "Cause_change_of_position_on_a_scale": ["Agent", "Attribute", "Cause", "Difference", "Item", "Value_1", "Value_2"],
        "Cause_to_amalgamate": ["Agent", "Part_1", "Part_2", "Parts", "Whole"],
        "Cause_to_make_progress": ["Agent", "Project"],
        "Change": ["Agent", "Attribute", "Cause", "Entity", "Final_category", "Final_value", "Initial_category"],
        "Change_of_leadership": ["Body", "New_leader", "Old_leader", "Old_order", "Role", "Selector"],
        "Check": ["Inspector", "Means", "Unconfirmed_content"],
        "Choosing": ["Chosen", "Cognizer", "Possibilities"],
        "Collaboration": ["Partners", "Undertaking"],
        "Come_together": ["Configuration", "Individuals", "Place"],
        "Coming_to_be": ["Components", "Entity", "Place", "Time"],
        "Coming_to_believe": ["Cognizer", "Content", "Means"],
        "Commerce_buy": ["Buyer", "Goods", "Seller"],
        "Commerce_pay": ["Buyer", "Goods", "Money", "Seller"],
        "Commerce_sell": ["Buyer", "Goods", "Money", "Seller"],
        "Commitment": ["Addressee", "Message", "Speaker"],
        "Committing_crime": ["Crime", "Instrument", "Perpetrator"],
        "Communication": ["Addressee", "Interlocutors", "Message", "Speaker", "Topic", "Trigger"],
        "Competition": ["Competition", "Participants", "Venue"],
        "Confronting_problem": ["Activity", "Experiencer"],
        "Connect": ["Figures", "Ground"],
        "Conquering": ["Conqueror", "Means", "Theme"],
        "Containing": ["Container", "Contents"],
        "Control": ["Controlling_variable", "Dependent_variable"],
        "Convincing": ["Addressee", "Content", "Speaker", "Topic"],
        "Cost": ["Asset", "Goods", "Intended_event", "Payer", "Rate"],
        "Create_artwork": ["Activity", "Culture"],
        "Creating": ["Cause", "Created_entity", "Creator"],
        "Criminal_investigation": ["Incident", "Investigator", "Suspect"],
        "Cure": ["Affliction", "Medication", "Patient", "Treatment"],
        "Damaging": ["Agent", "Cause", "Patient"],
        "Death": ["Deceased"],
        "Deciding": ["Cognizer", "Decision"],
        "Defending": ["Assailant", "Defender", "Instrument", "Victim"],
        "Departing": ["Goal", "Path", "Source", "Traveller"],
        "Destroying": ["Cause", "Destroyer", "Means", "Patient"],
        "Dispersal": ["Agent", "Cause", "Goal_area", "Individuals"],
        "Earnings_and_losses": ["Earner", "Earnings", "Goods"],
        "Education_teaching": ["Course", "Fact", "Role", "Skill", "Student", "Subject", "Teacher"],
        "Emergency": ["Place", "Undesirable_event"],
        "Employment": ["Employee", "Employer", "Field", "Place_of_employment", "Position", "Task", "Type"],
        "Emptying": ["Agent", "Cause", "Source", "Theme"],
        "Exchange": ["Exchanger_1", "Exchanger_2", "Exchangers", "Theme_1", "Theme_2", "Themes"],
        "Expansion": ["Agent", "Dimension", "Initial_size", "Item", "Result_size"],
        "Filling": ["Agent", "Cause", "Goal", "Theme"],
        "GetReady": ["Activity", "Protagonist"],
        "Getting": ["Means", "Recipient", "Source", "Theme"],
        "Giving": ["Offerer", "Recipient", "Theme"],
        "Hindering": ["Action", "Hindrance", "Protagonist"],
        "Hold": ["Entity", "Manipulator"],
        "Hostile_encounter": ["Instrument", "Issue", "Purpose", "Side_1", "Side_2", "Sides"],
        "Influence": ["Action", "Agent", "Behavior", "Cognizer", "Product", "Situation"],
        "Ingestion": ["Ingestibles", "Ingestor"],
        "Judgment_communication": ["Addressee", "Communicator", "Evaluee", "Medium", "Reason", "Topic"],
        "Killing": ["Cause", "Instrument", "Killer", "Means", "Victim"],
        "Know": ["Cognizer", "Evidence", "Instrument", "Means", "Phenomenon", "Topic"],
        "Labeling": ["Entity", "Label", "Speaker"],
        "Legality": ["Action", "Object"],
        "Manufacturing": ["Factory", "Instrument", "Producer", "Product", "Resource"],
        "Motion": ["Agent", "Area", "Cause", "Distance", "Goal", "Means", "Path", "Source", "Speed", "Theme"],
        "Motion_directional": ["Area", "Direction", "Goal", "Path", "Source", "Theme"],
        "Openness": ["Barrier", "Theme", "Useful_location"],
        "Participation": ["Event", "Participants"],
        "Perception_active": ["Direction", "Perceiver_agentive", "Phenomenon"],
        "Placing": ["Agent", "Cause", "Location", "Theme"],
        "Practice": ["Action", "Agent", "Occasion"],
        "Presence": ["Circumstances", "Duration", "Entity", "Inherent_purpose", "Place", "Time"],
        "Preventing_or_letting": ["Agent", "Event", "Means", "Potential_hindrance"],
        "Process_end": ["Agent", "Cause", "Final_subevent", "Process", "State", "Time"],
        "Process_start": ["Agent", "Event", "Initial_subevent", "Time"],
        "Protest": ["Addressee", "Arguer", "Content"],
        "Quarreling": ["Arguer2", "Arguers", "Issue"],
        "Ratification": ["Proposal", "Ratifier"],
        "Receiving": ["Donor", "Recipient", "Theme"],
        "Recovering": ["Agent", "Entity", "Means"],
        "Removing": ["Agent", "Cause", "Goal", "Source", "Theme"],
        "Request": ["Addressee", "Medium", "Message", "Speaker"],
        "Research": ["Field", "Researcher", "Topic"],
        "Resolve_problem": ["Agent", "Cause", "Means", "Problem"],
        "Response": ["Agent", "Responding_entity", "Response", "Trigger"],
        "Reveal_secret": ["Addressee", "Information", "Speaker", "Topic"],
        "Revenge": ["Avenger", "Injured_party", "Injury", "Offender", "Punishment"],
        "Rite": ["Member", "Object", "Type"],
        "Scrutiny": ["Cognizer", "Ground", "Instrument", "Phenomenon", "Unwanted_entity"],
        "Self_motion": ["Direction", "Distance", "Goal", "Path", "Self_mover", "Source"],
        "Sending": ["Goal", "Means", "Recipient", "Sender", "Source", "Theme", "Transferors", "Vehicle"],
        "Sign_agreement": ["Agreement", "Signatory"],
        "Social_event": ["Attendees", "Beneficiary", "Host", "Occasion", "Social_event"],
        "Statement": ["Addressee", "Medium", "Message", "Speaker"],
        "Supply": ["Imposed_purpose", "Recipient", "Supplier", "Theme"],
        "Supporting": ["Supported", "Supporter"],
        "Telling": ["Addressee", "Message", "Speaker"],
        "Terrorism": ["Act", "Instrument", "Terrorist", "Victim"],
        "Testing": ["Circumstances", "Means", "Product", "Result", "Tested_property", "Tester"],
        "Theft": ["Goods", "Instrument", "Means", "Perpetrator", "Source", "Victim"],
        "Traveling": ["Area", "Distance", "Entity", "Goal", "Means", "Path", "Purpose", "Traveler"],
        "Using": ["Agent", "Instrument", "Means", "Purpose"],
        "Wearing": ["Body_location", "Clothing", "Wearer"],
        "Writing": ["Addressee", "Author", "Instrument", "Text"],
    },
    "maven": {
        "Achieve": [],
        "Action": [],
        "Adducing": [],
        "Agree_or_refuse_to_act": [],
        "Aiming": [],
        "Arranging": [],
        "Arrest": [],
        "Arriving": [],
        "Assistance": [],
        "Attack": [],
        "Award": [],
        "Bearing_arms": [],
        "Becoming": [],
        "Becoming_a_member": [],
        "Being_in_operation": [],
        "Besieging": [],
        "Bodily_harm": [],
        "Body_movement": [],
        "Breathing": [],
        "Bringing": [],
        "Building": [],
        "Carry_goods": [],
        "Catastrophe": [],
        "Causation": [],
        "Cause_change_of_position_on_a_scale": [],
        "Cause_change_of_strength": [],
        "Cause_to_amalgamate": [],
        "Cause_to_be_included": [],
        "Cause_to_make_progress": [],
        "Change": [],
        "Change_event_time": [],
        "Change_of_leadership": [],
        "Change_sentiment": [],
        "Change_tool": [],
        "Check": [],
        "Choosing": [],
        "Collaboration": [],
        "Come_together": [],
        "Coming_to_be": [],
        "Coming_to_believe": [],
        "Commerce_buy": [],
        "Commerce_pay": [],
        "Commerce_sell": [],
        "Commitment": [],
        "Committing_crime": [],
        "Communication": [],
        "Competition": [],
        "Confronting_problem": [],
        "Connect": [],
        "Conquering": [],
        "Containing": [],
        "Control": [],
        "Convincing": [],
        "Cost": [],
        "Create_artwork": [],
        "Creating": [],
        "Criminal_investigation": [],
        "Cure": [],
        "Damaging": [],
        "Death": [],
        "Deciding": [],
        "Defending": [],
        "Departing": [],
        "Destroying": [],
        "Dispersal": [],
        "Earnings_and_losses": [],
        "Education_teaching": [],
        "Emergency": [],
        "Employment": [],
        "Emptying": [],
        "Escaping": [],
        "Exchange": [],
        "Expansion": [],
        "Expend_resource": [],
        "Expressing_publicly": [],
        "Extradition": [],
        "Filling": [],
        "Forming_relationships": [],
        "GetReady": [],
        "Getting": [],
        "GiveUp": [],
        "Giving": [],
        "Having_or_lacking_access": [],
        "Hiding_objects": [],
        "Hindering": [],
        "Hold": [],
        "Hostile_encounter": [],
        "Imposing_obligation": [],
        "Incident": [],
        "Influence": [],
        "Ingestion": [],
        "Institutionalization": [],
        "Judgment_communication": [],
        "Justifying": [],
        "Kidnapping": [],
        "Killing": [],
        "Know": [],
        "Labeling": [],
        "Legal_rulings": [],
        "Legality": [],
        "Lighting": [],
        "Limiting": [],
        "Manufacturing": [],
        "Military_operation": [],
        "Motion": [],
        "Motion_directional": [],
        "Name_conferral": [],
        "Openness": [],
        "Participation": [],
        "Patrolling": [],
        "Perception_active": [],
        "Placing": [],
        "Practice": [],
        "Presence": [],
        "Preserving": [],
        "Preventing_or_letting": [],
        "Prison": [],
        "Process_end": [],
        "Process_start": [],
        "Protest": [],
        "Publishing": [],
        "Quarreling": [],
        "Ratification": [],
        "Receiving": [],
        "Recording": [],
        "Recovering": [],
        "Reforming_a_system": [],
        "Releasing": [],
        "Removing": [],
        "Renting": [],
        "Reporting": [],
        "Request": [],
        "Rescuing": [],
        "Research": [],
        "Resolve_problem": [],
        "Response": [],
        "Reveal_secret": [],
        "Revenge": [],
        "Rewards_and_punishments": [],
        "Risk": [],
        "Rite": [],
        "Robbery": [],
        "Scouring": [],
        "Scrutiny": [],
        "Self_motion": [],
        "Sending": [],
        "Sign_agreement": [],
        "Social_event": [],
        "Statement": [],
        "Submitting_documents": [],
        "Supply": [],
        "Supporting": [],
        "Surrendering": [],
        "Surrounding": [],
        "Suspicion": [],
        "Telling": [],
        "Temporary_stay": [],
        "Terrorism": [],
        "Testing": [],
        "Theft": [],
        "Traveling": [],
        "Use_firearm": [],
        "Using": [],
        "Violence": [],
        "Vocalizations": [],
        "Warning": [],
        "Wearing": [],
        "Writing": [],
    },
    "mee-en": {
        "Business_START-ORG": ["Agent", "Organization", "Place", "Time"], 
        "Conflict_Attack": ["Attacker", "Instrument", "Place", "Target", "Time"], 
        "Conflict_Demonstrate": ["Entity", "Place", "Time"], 
        "Contact_Meet": ["Entity", "Place", "Time"], 
        "Contact_Phone-Write": ["Entity", "Time"], 
        "Justice_Arrest-Jail": ["Agent", "Crime", "Person", "Place", "Time"], 
        "Life_Be-Born": ["Person", "Place", "Time"], 
        "Life_Die": ["Agent", "Instrument", "Place", "Time", "Victim"], 
        "Life_Divorce": ["Person", "Place", "Time"], 
        "Life_Injure": ["Agent", "Instrument", "Place", "Time", "Victim"], 
        "Life_Marry": ["Person", "Place", "Time"], 
        "Movement_Transport": ["Agent", "Artifact",  "Destination", "Origin", "Time", "Vehicle"], 
        "Personnel_End-Position": ["Entity", "Person", "Place", "Position", "Time"], 
        "Personnel_Start-Position": ["Entity", "Person", "Place", "Position", "Time"], 
        "Transaction_Transfer-Money": ["Beneficiary", "Giver", "Money", "Place", "Recipient", "Time"], 
        "Transaction_Transfer-Ownership": ["Artifact", "Beneficiary", "Buyer", "Money", "Place", "Price", "Seller", "Time"], 
    }, 
    "rams": {
        "artifactexistence.damagedestroy.damage": ["artifact", "damager", "instrument", "place"],
        "artifactexistence.damagedestroy.destroy": ["artifact", "destroyer", "instrument", "place"],
        "artifactexistence.damagedestroy.n/a": ["artifact", "damagerdestroyer", "instrument", "place"],
        "conflict.attack.airstrikemissilestrike": ["attacker", "instrument", "place", "target"],
        "conflict.attack.biologicalchemicalpoisonattack": ["attacker", "instrument", "place", "target"],
        "conflict.attack.bombing": ["attacker", "instrument", "place", "target"],
        "conflict.attack.firearmattack": ["attacker", "instrument", "place", "target"],
        "conflict.attack.hanging": ["attacker", "instrument", "place", "target"],
        "conflict.attack.invade": ["attacker", "instrument", "place", "target"],
        "conflict.attack.n/a": ["attacker", "instrument", "place", "target"],
        "conflict.attack.selfdirectedbattle": ["attacker", "instrument", "place", "target"],
        "conflict.attack.setfire": ["attacker", "instrument", "place", "target"],
        "conflict.attack.stabbing": ["attacker", "instrument", "place", "target"],
        "conflict.attack.stealrobhijack": ["artifact", "attacker", "instrument", "place", "target"],
        "conflict.attack.strangling": ["attacker", "instrument", "place", "target"],
        "conflict.demonstrate.marchprotestpoliticalgathering": ["demonstrator", "place"],
        "conflict.demonstrate.n/a": ["demonstrator", "place"],
        "conflict.yield.n/a": ["place", "recipient", "yielder"],
        "conflict.yield.retreat": ["destination", "origin", "retreater"],
        "conflict.yield.surrender": ["place", "recipient", "surrenderer"],
        "contact.collaborate.correspondence": ["participant", "place"],
        "contact.collaborate.meet": ["participant", "place"],
        "contact.collaborate.n/a": ["participant", "place"],
        "contact.commandorder.broadcast": ["communicator", "place", "recipient"],
        "contact.commandorder.correspondence": ["communicator", "place", "recipient"],
        "contact.commandorder.meet": ["communicator", "place", "recipient"],
        "contact.commandorder.n/a": ["communicator", "place", "recipient"],
        "contact.commitmentpromiseexpressintent.broadcast": ["communicator", "place", "recipient"],
        "contact.commitmentpromiseexpressintent.correspondence": ["communicator", "place", "recipient"],
        "contact.commitmentpromiseexpressintent.meet": ["communicator", "place", "recipient"],
        "contact.commitmentpromiseexpressintent.n/a": ["communicator", "place", "recipient"],
        "contact.discussion.correspondence": ["participant", "place"],
        "contact.discussion.meet": ["participant", "place"],
        "contact.discussion.n/a": ["participant", "place"],
        "contact.funeralvigil.meet": ["deceased", "participant", "place"],
        "contact.funeralvigil.n/a": ["deceased", "participant", "place"],
        "contact.mediastatement.broadcast": ["communicator", "place", "recipient"],
        "contact.mediastatement.n/a": ["communicator", "place", "recipient"],
        "contact.negotiate.correspondence": ["participant", "place"],
        "contact.negotiate.meet": ["participant", "place"],
        "contact.negotiate.n/a": ["participant", "place"],
        "contact.prevarication.broadcast": ["communicator", "place", "recipient"],
        "contact.prevarication.correspondence": ["communicator", "place", "recipient"],
        "contact.prevarication.meet": ["communicator", "place", "recipient"],
        "contact.prevarication.n/a": ["communicator", "place", "recipient"],
        "contact.publicstatementinperson.broadcast": ["communicator", "place", "recipient"],
        "contact.publicstatementinperson.n/a": ["communicator", "place", "recipient"],
        "contact.requestadvise.broadcast": ["communicator", "place", "recipient"],
        "contact.requestadvise.correspondence": ["communicator", "place", "recipient"],
        "contact.requestadvise.meet": ["communicator", "place", "recipient"],
        "contact.requestadvise.n/a": ["communicator", "place", "recipient"],
        "contact.threatencoerce.broadcast": ["communicator", "place", "recipient"],
        "contact.threatencoerce.correspondence": ["communicator", "place", "recipient"],
        "contact.threatencoerce.meet": ["communicator", "place", "recipient"],
        "contact.threatencoerce.n/a": ["communicator", "place", "recipient"],
        "disaster.accidentcrash.accidentcrash": ["crashobject", "driverpassenger", "place", "vehicle"],
        "disaster.fireexplosion.fireexplosion": ["fireexplosionobject", "instrument", "place"],
        "government.agreements.acceptagreementcontractceasefire": ["participant", "place"],
        "government.agreements.n/a": ["participant", "place"],
        "government.agreements.rejectnullifyagreementcontractceasefire": ["otherparticipant", "place", "rejecternullifier"],
        "government.agreements.violateagreement": ["otherparticipant", "place", "violator"],
        "government.formation.mergegpe": ["participant", "place"],
        "government.formation.n/a": ["founder", "gpe", "place"],
        "government.formation.startgpe": ["founder", "gpe", "place"],
        "government.legislate.legislate": ["governmentbody", "law", "place"],
        "government.spy.spy": ["beneficiary", "observedentity", "place", "spy"],
        "government.vote.castvote": ["ballot", "candidate", "place", "result", "voter"],
        "government.vote.n/a": ["ballot", "candidate", "place", "result", "voter"],
        "government.vote.violationspreventvote": ["ballot", "candidate", "place", "preventer", "voter"],
        "inspection.sensoryobserve.inspectpeopleorganization": ["inspectedentity", "inspector", "place"],
        "inspection.sensoryobserve.monitorelection": ["monitor", "monitoredentity", "place"],
        "inspection.sensoryobserve.n/a": ["observedentity", "observer", "place"],
        "inspection.sensoryobserve.physicalinvestigateinspect": ["inspectedentity", "inspector", "place"],
        "justice.arrestjaildetain.arrestjaildetain": ["crime", "detainee", "jailer", "place"],
        "justice.initiatejudicialprocess.chargeindict": ["crime", "defendant", "judgecourt", "place", "prosecutor"],
        "justice.initiatejudicialprocess.n/a": ["crime", "defendant", "judgecourt", "place", "prosecutor"],
        "justice.initiatejudicialprocess.trialhearing": ["crime", "defendant", "judgecourt", "place", "prosecutor"],
        "justice.investigate.investigatecrime": ["crime", "defendant", "investigator", "place"],
        "justice.investigate.n/a": ["defendant", "investigator", "place"],
        "justice.judicialconsequences.convict": ["crime", "defendant", "judgecourt", "place"],
        "justice.judicialconsequences.execute": ["crime", "defendant", "executioner", "place"],
        "justice.judicialconsequences.extradite": ["crime", "defendant", "destination", "extraditer", "origin"],
        "justice.judicialconsequences.n/a": ["crime", "defendant", "judgecourt", "place"],
        "life.die.deathcausedbyviolentevents": ["instrument", "killer", "place", "victim"],
        "life.die.n/a": ["place", "victim"],
        "life.die.nonviolentdeath": ["place", "victim"],
        "life.injure.illnessdegradationhungerthirst": ["place", "victim"],
        "life.injure.illnessdegradationphysical": ["victim"],
        "life.injure.injurycausedbyviolentevents": ["injurer", "instrument", "place", "victim"],
        "life.injure.n/a": ["injurer", "place", "victim"],
        "manufacture.artifact.build": ["artifact", "instrument", "manufacturer", "place"],
        "manufacture.artifact.createintellectualproperty": ["artifact", "instrument", "manufacturer", "place"],
        "manufacture.artifact.createmanufacture": ["artifact", "instrument", "manufacturer", "place"],
        "manufacture.artifact.n/a": ["artifact", "instrument", "manufacturer", "place"],
        "movement.transportartifact.bringcarryunload": ["artifact", "destination", "origin", "transporter", "vehicle"],
        "movement.transportartifact.disperseseparate": ["artifact", "destination", "origin", "transporter", "vehicle"],
        "movement.transportartifact.fall": ["artifact", "destination", "origin"],
        "movement.transportartifact.grantentry": ["artifact", "destination", "origin", "transporter"],
        "movement.transportartifact.hide": ["artifact", "hidingplace", "origin", "transporter", "vehicle"],
        "movement.transportartifact.n/a": ["artifact", "destination", "origin", "transporter", "vehicle"],
        "movement.transportartifact.nonviolentthrowlaunch": ["artifact", "destination", "origin", "transporter", "vehicle"],
        "movement.transportartifact.prevententry": ["artifact", "destination", "origin", "preventer", "transporter"],
        "movement.transportartifact.preventexit": ["artifact", "destination", "origin", "preventer", "transporter"],
        "movement.transportartifact.receiveimport": ["artifact", "destination", "origin", "transporter", "vehicle"],
        "movement.transportartifact.sendsupplyexport": ["artifact", "destination", "origin", "transporter", "vehicle"],
        "movement.transportartifact.smuggleextract": ["artifact", "destination", "origin", "transporter", "vehicle"],
        "movement.transportperson.bringcarryunload": ["destination", "origin", "passenger", "transporter", "vehicle"],
        "movement.transportperson.disperseseparate": ["destination", "origin", "passenger", "transporter", "vehicle"],
        "movement.transportperson.evacuationrescue": ["destination", "origin", "passenger", "transporter", "vehicle"],
        "movement.transportperson.fall": ["destination", "origin", "passenger"],
        "movement.transportperson.grantentryasylum": ["destination", "granter", "origin", "passenger", "transporter"],
        "movement.transportperson.hide": ["hidingplace", "origin", "passenger", "transporter", "vehicle"],
        "movement.transportperson.n/a": ["destination", "origin", "passenger", "transporter", "vehicle"],
        "movement.transportperson.prevententry": ["destination", "origin", "passenger", "preventer", "transporter"],
        "movement.transportperson.preventexit": ["destination", "origin", "passenger", "preventer", "transporter"],
        "movement.transportperson.selfmotion": ["destination", "origin", "transporter"],
        "movement.transportperson.smuggleextract": ["destination", "origin", "passenger", "transporter", "vehicle"],
        "personnel.elect.n/a": ["candidate", "place", "voter"],
        "personnel.elect.winelection": ["candidate", "place", "voter"],
        "personnel.endposition.firinglayoff": ["employee", "place", "placeofemployment"],
        "personnel.endposition.n/a": ["employee", "place", "placeofemployment"],
        "personnel.endposition.quitretire": ["employee", "place", "placeofemployment"],
        "personnel.startposition.hiring": ["employee", "place", "placeofemployment"],
        "personnel.startposition.n/a": ["employee", "place", "placeofemployment"],
        "transaction.transaction.embargosanction": ["artifactmoney", "giver", "place", "preventer", "recipient"],
        "transaction.transaction.giftgrantprovideaid": ["beneficiary", "giver", "place", "recipient"],
        "transaction.transaction.n/a": ["beneficiary", "participant", "place"],
        "transaction.transaction.transfercontrol": ["beneficiary", "giver", "place", "recipient", "territoryorfacility"],
        "transaction.transfermoney.borrowlend": ["beneficiary", "giver", "money", "place", "recipient"],
        "transaction.transfermoney.embargosanction": ["giver", "money", "place", "preventer", "recipient"],
        "transaction.transfermoney.giftgrantprovideaid": ["beneficiary", "giver", "money", "place", "recipient"],
        "transaction.transfermoney.n/a": ["beneficiary", "giver", "money", "place", "recipient"],
        "transaction.transfermoney.payforservice": ["beneficiary", "giver", "money", "place", "recipient"],
        "transaction.transfermoney.purchase": ["beneficiary", "giver", "money", "place", "recipient"],
        "transaction.transferownership.borrowlend": ["artifact", "beneficiary", "giver", "place", "recipient"],
        "transaction.transferownership.embargosanction": ["artifact", "giver", "place", "preventer", "recipient"],
        "transaction.transferownership.giftgrantprovideaid": ["artifact", "beneficiary", "giver", "place", "recipient"],
        "transaction.transferownership.n/a": ["artifact", "beneficiary", "giver", "place", "recipient"],
        "transaction.transferownership.purchase": ["artifact", "beneficiary", "giver", "place", "recipient"],  
    },
    "wikievents": {
        "ArtifactExistence.DamageDestroyDisableDismantle.Damage": ["Artifact", "Damager", "Instrument", "Place"],
        "ArtifactExistence.DamageDestroyDisableDismantle.Destroy": ["Artifact", "Destroyer", "Instrument", "Place"],
        "ArtifactExistence.DamageDestroyDisableDismantle.DisableDefuse": ["Artifact", "Disabler", "Instrument"],
        "ArtifactExistence.DamageDestroyDisableDismantle.Dismantle": ["Artifact", "Components", "Dismantler", "Instrument", "Place"],
        "ArtifactExistence.DamageDestroyDisableDismantle.Unspecified": ["Artifact", "DamagerDestroyer", "Instrument", "Place"],
        "ArtifactExistence.ManufactureAssemble.Unspecified": ["Artifact", "Components", "ManufacturerAssembler", "Place"],
        "Cognitive.IdentifyCategorize.Unspecified": ["IdentifiedObject", "IdentifiedRole", "Identifier", "Place"],
        "Cognitive.Inspection.SensoryObserve": ["Instrument", "ObservedEntity", "Observer", "Place"],
        "Cognitive.Research.Unspecified": ["Place", "Researcher", "Subject"],
        "Cognitive.TeachingTrainingLearning.Unspecified": ["Learner", "TeacherTrainer"],
        "Conflict.Attack.DetonateExplode": ["Attacker", "ExplosiveDevice", "Instrument", "Place", "Target"],
        "Conflict.Attack.Unspecified": ["Attacker", "Instrument", "Place", "Target"],
        "Conflict.Defeat.Unspecified": ["Defeated", "Place", "Victor"],
        "Conflict.Demonstrate.DemonstrateWithViolence": ["Demonstrator", "Regulator"],
        "Conflict.Demonstrate.Unspecified": ["Demonstrator", "Target", "Topic"],
        "Contact.Contact.Broadcast": ["Communicator", "Instrument", "Place", "Recipient", "Topic"],
        "Contact.Contact.Correspondence": ["Participant", "Place", "Topic"],
        "Contact.Contact.Meet": ["Participant", "Place", "Topic"],
        "Contact.Contact.Unspecified": ["Participant", "Place", "Topic"],
        "Contact.RequestCommand.Broadcast": ["Communicator", "Recipient"],
        "Contact.RequestCommand.Correspondence": ["Communicator", "Recipient", "Topic"],
        "Contact.RequestCommand.Meet": ["Communicator", "Recipient"],
        "Contact.RequestCommand.Unspecified": ["Communicator", "Place", "Recipient"],
        "Contact.ThreatenCoerce.Broadcast": ["Communicator", "Recipient"],
        "Contact.ThreatenCoerce.Correspondence": ["Communicator", "Recipient"],
        "Contact.ThreatenCoerce.Unspecified": ["Communicator", "Recipient"],
        "Control.ImpedeInterfereWith.Unspecified": ["Impeder", "Place"],
        "Disaster.Crash.Unspecified": ["CrashObject", "Place", "Vehicle"],
        "Disaster.DiseaseOutbreak.Unspecified": ["Place", "Victim"],
        "GenericCrime.GenericCrime.GenericCrime": ["Perpetrator", "Place", "Victim"],
        "Justice.Acquit.Unspecified": ["Defendant"],
        "Justice.ArrestJailDetain.Unspecified": ["Detainee", "Jailer", "Place"],
        "Justice.ChargeIndict.Unspecified": ["Defendant", "JudgeCourt", "Place", "Prosecutor"],
        "Justice.Convict.Unspecified": ["Defendant", "JudgeCourt"],
        "Justice.InvestigateCrime.Unspecified": ["Defendant", "Investigator", "ObservedEntity", "Observer", "Place"],
        "Justice.ReleaseParole.Unspecified": ["Defendant", "JudgeCourt"],
        "Justice.Sentence.Unspecified": ["Defendant", "JudgeCourt", "Place"],
        "Justice.TrialHearing.Unspecified": ["Defendant", "JudgeCourt", "Place", "Prosecutor"],
        "Life.Die.Unspecified": ["Killer", "Place", "Victim"],
        "Life.Infect.Unspecified": ["Victim"],
        "Life.Injure.Unspecified": ["BodyPart", "Injurer", "Instrument", "Victim"],
        "Medical.Intervention.Unspecified": ["Patient", "Place", "Treater"],
        "Movement.Transportation.Evacuation": ["Destination", "Origin", "PassengerArtifact", "Transporter"],
        "Movement.Transportation.IllegalTransportation": ["Destination", "PassengerArtifact", "Transporter", "Vehicle"],
        "Movement.Transportation.PreventPassage": ["Destination", "Origin", "PassengerArtifact", "Preventer", "Transporter", "Vehicle"],
        "Movement.Transportation.Unspecified": ["Destination", "Origin", "PassengerArtifact", "Transporter", "Vehicle"],
        "Personnel.EndPosition.Unspecified": ["Employee", "PlaceOfEmployment"],
        "Personnel.StartPosition.Unspecified": ["Employee", "Place", "PlaceOfEmployment", "Position"],
        "Transaction.Donation.Unspecified": ["ArtifactMoney", "Giver", "Recipient"],
        "Transaction.ExchangeBuySell.Unspecified": ["AcquiredEntity", "Giver", "PaymentBarter", "Recipient"],
    },
    "phee": {
        "Adverse_event": [
            "Combination_Drug",
            "Effect",
            "Subject",
            "Subject_Age",
            "Subject_Disorder",
            "Subject_Gender",
            "Subject_Population",
            "Subject_Race",
            "Treatment",
            "Treatment_Disorder",
            "Treatment_Dosage",
            "Treatment_Drug",
            "Treatment_Duration",
            "Treatment_Freq",
            "Treatment_Route",
            "Treatment_Time_elapsed",
          ],
        "Potential_therapeutic_event": [
            "Combination_Drug",
            "Effect",
            "Subject",
            "Subject_Age",
            "Subject_Disorder",
            "Subject_Gender",
            "Subject_Population",
            "Subject_Race",
            "Treatment",
            "Treatment_Disorder",
            "Treatment_Dosage",
            "Treatment_Drug",
            "Treatment_Duration",
            "Treatment_Freq",
            "Treatment_Route",
            "Treatment_Time_elapsed",
          ],
    },
    "casie": {
        "Attack:Databreach": [
            "Attack-Pattern",
            "Attacker",
            "Compromised-Data",
            "Damage-Amount",
            "Number-of-Data",
            "Number-of-Victim",
            "Place",
            "Purpose",
            "Time",
            "Tool",
            "Victim"
        ],
        "Attack:Phishing": [
            "Attack-Pattern",
            "Attacker",
            "Damage-Amount",
            "Place",
            "Purpose",
            "Time",
            "Tool",
            "Trusted-Entity",
            "Victim",
        ],
        "Attack:Ransom": [
            "Attack-Pattern",
            "Attacker",
            "Damage-Amount",
            "Payment-Method",
            "Place",
            "Price",
            "Time",
            "Tool",
            "Victim",
        ],
        "Vulnerability-related:DiscoverVulnerability": [
            "CVE",
            "Capabilities",
            "Discoverer",
            "Supported_Platform",
            "Time",
            "Vulnerability",
            "Vulnerable_System",
            "Vulnerable_System_Owner",
            "Vulnerable_System_Version",
        ],
        "Vulnerability-related:PatchVulnerability": [
            "CVE",
            "Issues-Addressed",
            "Patch",
            "Patch-Number",
            "Releaser",
            "Supported_Platform",
            "Time",
            "Vulnerability",
            "Vulnerable_System",
            "Vulnerable_System_Version",
        ],
    },
    "mlee": {
        "Acetylation": ["Theme"],
        "Binding": ["Site", "Theme", "Theme2"],
        "Blood_vessel_development": ["AtLoc", "FromLoc", "Theme"],
        "Breakdown": ["Theme"],
        "Catabolism": ["Theme"],
        "Cell_division": ["Theme"],
        "Cell_proliferation": ["Theme"],
        "DNA_methylation": ["Site", "Theme"],
        "Death": ["Theme"],
        "Dephosphorylation": ["Site", "Theme"],
        "Development": ["Theme"],
        "Dissociation": ["Theme"],
        "Gene_expression": ["Theme"],
        "Growth": ["Theme"],
        "Localization": ["AtLoc", "FromLoc", "Theme", "ToLoc"],
        "Metabolism": ["Theme"],
        "Negative_regulation": ["CSite", "Cause", "Site", "Theme"],
        "Pathway": ["Participant", "Participant2", "Participant3", "Participant4"],
        "Phosphorylation": ["Site", "Theme"],
        "Planned_process": ["Instrument", "Instrument2", "Theme", "Theme2"],
        "Positive_regulation": ["CSite", "Cause", "Site", "Theme", "Theme2"],
        "Protein_processing": ["Theme"],
        "Regulation": ["CSite", "Cause", "Site", "Theme"],
        "Remodeling": ["Theme"],
        "Reproduction": ["Theme"],
        "Synthesis": ["Theme"],
        "Transcription": ["Theme"],
        "Translation": ["Theme"],
        "Ubiquitination": ["Theme"],
    }, 
    "genia2011": {
        "Binding": ["Site", "Site2", "Theme", "Theme2", "Theme3", "Theme4"],
        "Gene_expression": ["Theme"],
        "Localization": ["AtLoc", "Theme", "ToLoc"],
        "Negative_regulation": ["CSite", "Cause", "Site", "Theme"],
        "Phosphorylation": ["Site", "Theme"],
        "Positive_regulation": ["CSite", "Cause", "Site", "Theme"],
        "Protein_catabolism": ["Theme"],
        "Regulation": ["CSite", "Cause", "Site", "Theme"],
        "Transcription": ["Theme"],
    },
    "genia2013": {
        "Acetylation": ["Site", "Theme"],
        "Binding": ["Site", "Site2", "Theme", "Theme2"],
        "Deacetylation": ["Cause", "Site", "Theme"],
        "Gene_expression": ["Theme"],
        "Localization": ["Theme", "ToLoc"],
        "Negative_regulation": ["CSite", "Cause", "Site", "Theme"],
        "Phosphorylation": ["Cause", "Site", "Theme"],
        "Positive_regulation": ["CSite", "Cause", "Site", "Theme"],
        "Protein_catabolism": ["Theme"],
        "Protein_modification": ["Theme"],
        "Regulation": ["CSite", "Cause", "Site", "Theme"],
        "Transcription": ["Theme"],
        "Ubiquitination": ["Cause", "Site", "Theme"],
    },
    "speed": {
        "control": [], 
        "cure": [], 
        "death": [], 
        "infect": [], 
        "prevent": [], 
        "spread": [], 
        "symptom": [], 
    }, 
    "muc4": {
        "Dummy": ["PerpInd", "PerpOrg", "Target", "Victim", "Weapon"],
    }, 
}

event_type_tags = {
    "ace05-en": {
        "Business:Declare-Bankruptcy": "Business Declare Bankruptcy", 
        "Business:End-Org": "Business End Organization", 
        "Business:Merge-Org": "Business Merge Organization", 
        "Business:Start-Org": "Business Start Organization", 
        "Conflict:Attack": "Conflict Attack", 
        "Conflict:Demonstrate": "Conflict Demonstrate", 
        "Contact:Meet": "Contact Meet", 
        "Contact:Phone-Write": "Contact Phone Write", 
        "Justice:Acquit": "Justice Acquit", 
        "Justice:Appeal": "Justice Appeal", 
        "Justice:Arrest-Jail": "Justice Arrest Jail", 
        "Justice:Charge-Indict": "Justice Charge Indict", 
        "Justice:Convict": "Justice Convict", 
        "Justice:Execute": "Justice Execute", 
        "Justice:Extradite": "Justice Extradite", 
        "Justice:Fine": "Justice Fine", 
        "Justice:Pardon": "Justice Pardon", 
        "Justice:Release-Parole": "Justice Release Parole", 
        "Justice:Sentence": "Justice Sentence", 
        "Justice:Sue": "Justice Sue", 
        "Justice:Trial-Hearing": "Justice Trial Hearing", 
        "Life:Be-Born": "Life Born", 
        "Life:Die": "Life Die", 
        "Life:Divorce": "Life Divorce", 
        "Life:Injure": "Life Injure", 
        "Life:Marry": "Life Marry", 
        "Movement:Transport": "Movement Transport", 
        "Personnel:Elect": "Personnel Elect", 
        "Personnel:End-Position": "Personnel End Position", 
        "Personnel:Nominate": "Personnel Nominate", 
        "Personnel:Start-Position": "Personnel Start-Position", 
        "Transaction:Transfer-Money": "Transaction Transfer Money", 
        "Transaction:Transfer-Ownership": "Transaction Transfer Ownership", 
    }, 
    "richere-en": {
        "Business:Start-Org": "Business Start Organization", 
        "Business:Merge-Org": "Business Merge Organization", 
        "Business:End-Org": "Business End Organization", 
        "Business:Declare-Bankruptcy": "Business Declare Bankruptcy", 
        "Conflict:Attack": "Conflict Attack", 
        "Conflict:Demonstrate": "Conflict Demonstrate", 
        "Contact:Meet": "Contact Meet", 
        "Contact:Correspondence": "Contact Correspondence", 
        "Contact:Broadcast": "Contact Broadcast", 
        "Contact:Contact": "Contact Contact", 
        "Justice:Arrest-Jail": "Justice Arrest Jail", 
        "Justice:Release-Parole": "Justice Release Parole", 
        "Justice:Trial-Hearing": "Justice Trial Hearing", 
        "Justice:Charge-Indict": "Justice Charge Indict", 
        "Justice:Sue": "Justice Sue", 
        "Justice:Convict": "Justice Convict", 
        "Justice:Appeal": "Justice Appeal", 
        "Justice:Sentence": "Justice Sentence", 
        "Justice:Fine": "Justice Fine", 
        "Justice:Execute": "Justice Execute", 
        "Justice:Extradite": "Justice Extradite", 
        "Justice:Acquit": "Justice Acquit", 
        "Justice:Pardon": "Justice Pardon", 
        "Life:Be-Born": "Life Born", 
        "Life:Marry": "Life Marry", 
        "Life:Divorce": "Life Divorce", 
        "Life:Injure": "Life Injure", 
        "Life:Die": "Life Die", 
        "Movement:Transport-Person": "Movement Transport Person", 
        "Movement:Transport-Artifact": "Movement Transport Artifact", 
        "Manufacture:Artifact": "Manufacture Artifact", 
        "Personnel:Start-Position": "Personnel Start Position", 
        "Personnel:End-Position": "Personnel End Position", 
        "Personnel:Nominate": "Personnel Nominate", 
        "Personnel:Elect": "Personnel Elect", 
        "Transaction:Transfer-Ownership": "Transaction Transfer Ownership", 
        "Transaction:Transfer-Money": "Transaction Transfer Money", 
        "Transaction:Transaction": "Transaction Transaction", 
    }, 
    "m2e2": {
        "Conflict:Attack": "Conflict Attack", 
        "Conflict:Demonstrate": "Conflict Demonstrate", 
        "Contact:Meet": "Contact Meet", 
        "Contact:Phone-Write": "Contact Phone Write", 
        "Justice:Arrest-Jail": "Justice Arrest Jail", 
        "Life:Die": "Life Die", 
        "Movement:Transport": "Movement Transport", 
        "Transaction:Transfer-Money": "Transaction Transfer Money", 
    }, 
    "geneva": {
        "Achieve": "Achieve",
        "Action": "Action",
        "Adducing": "Adducing",
        "Agree_or_refuse_to_act": "Agree Refuse Act",
        "Arranging": "Arranging",
        "Arrest": "Arrest",
        "Arriving": "Arriving",
        "Assistance": "Assistance",
        "Attack": "Attack",
        "Bearing_arms": "Bearing Arms",
        "Becoming": "Becoming",
        "Becoming_a_member": "Becoming A Member",
        "Bodily_harm": "Bodily Harm",
        "Bringing": "Bringing",
        "Building": "Building",
        "Catastrophe": "Catastrophe",
        "Causation": "Causation",
        "Cause_change_of_position_on_a_scale": "Cause Change Position on Acale",
        "Cause_to_amalgamate": "Cause Amalgamate",
        "Cause_to_make_progress": "Cause Make Progress",
        "Change": "Change",
        "Change_of_leadership": "Change Leadership",
        "Check": "Check",
        "Choosing": "Choosing",
        "Collaboration": "Collaboration",
        "Come_together": "Come Together",
        "Coming_to_be": "Coming",
        "Coming_to_believe": "Coming Believe",
        "Commerce_buy": "Commerce Buy",
        "Commerce_pay": "Commerce Pay",
        "Commerce_sell": "Commerce Sell",
        "Commitment": "Commitment",
        "Committing_crime": "Committing Crime",
        "Communication": "Communication",
        "Competition": "Competition",
        "Confronting_problem": "Confronting Problem",
        "Connect": "Connect",
        "Conquering": "Conquering",
        "Containing": "Containing",
        "Control": "Control",
        "Convincing": "Convincing",
        "Cost": "Cost",
        "Create_artwork": "Create Artwork",
        "Creating": "Creating",
        "Criminal_investigation": "Criminal Investigation",
        "Cure": "Cure",
        "Damaging": "Damaging",
        "Death": "Death",
        "Deciding": "Deciding",
        "Defending": "Defending",
        "Departing": "Departing",
        "Destroying": "Destroying",
        "Dispersal": "Dispersal",
        "Earnings_and_losses": "Earnings Losses",
        "Education_teaching": "Education Teaching",
        "Emergency": "Emergency",
        "Employment": "Employment",
        "Emptying": "Emptying",
        "Exchange": "Exchange",
        "Expansion": "Expansion",
        "Filling": "Filling",
        "GetReady": "Get Ready",
        "Getting": "Getting",
        "Giving": "Giving",
        "Hindering": "Hindering",
        "Hold": "Hold",
        "Hostile_encounter": "Hostile Encounter",
        "Influence": "Influence",
        "Ingestion": "Ingestion",
        "Judgment_communication": "Judgment Communication",
        "Killing": "Killing",
        "Know": "Know",
        "Labeling": "Labeling",
        "Legality": "Legality",
        "Manufacturing": "Manufacturing",
        "Motion": "Motion",
        "Motion_directional": "Motion Directional",
        "Openness": "Openness",
        "Participation": "Participation",
        "Perception_active": "Perception Active",
        "Placing": "Placing",
        "Practice": "Practice",
        "Presence": "Presence",
        "Preventing_or_letting": "Preventing Letting",
        "Process_end": "Process End",
        "Process_start": "Process Start",
        "Protest": "Protest",
        "Quarreling": "Quarreling",
        "Ratification": "Ratification",
        "Receiving": "Receiving",
        "Recovering": "Recovering",
        "Removing": "Removing",
        "Request": "Request",
        "Research": "Research",
        "Resolve_problem": "Resolve Problem",
        "Response": "Response",
        "Reveal_secret": "Reveal Secret",
        "Revenge": "Revenge",
        "Rite": "Rite",
        "Scrutiny": "Scrutiny",
        "Self_motion": "Self Motion",
        "Sending": "Sending",
        "Sign_agreement": "Sign Agreement",
        "Social_event": "Social Event",
        "Statement": "Statement",
        "Supply": "Supply",
        "Supporting": "Supporting",
        "Telling": "Telling",
        "Terrorism": "Terrorism",
        "Testing": "Testing",
        "Theft": "Theft",
        "Traveling": "Traveling",
        "Using": "Using",
        "Wearing": "Wearing",
        "Writing": "Writing",
    }, 
    "maven": {
         "Achieve": "Achieve",
         "Action": "Action",
         "Adducing": "Adducing",
         "Agree_or_refuse_to_act": "Agree Or Refuse To Act",
         "Aiming": "Aiming",
         "Arranging": "Arranging",
         "Arrest": "Arrest",
         "Arriving": "Arriving",
         "Assistance": "Assistance",
         "Attack": "Attack",
         "Award": "Award",
         "Bearing_arms": "Bearing Arms",
         "Becoming": "Becoming",
         "Becoming_a_member": "Becoming A Member",
         "Being_in_operation": "Being In Operation",
         "Besieging": "Besieging",
         "Bodily_harm": "Bodily Harm",
         "Body_movement": "Body Movement",
         "Breathing": "Breathing",
         "Bringing": "Bringing",
         "Building": "Building",
         "Carry_goods": "Carry Goods",
         "Catastrophe": "Catastrophe",
         "Causation": "Causation",
         "Cause_change_of_position_on_a_scale": "Cause Change Of Position On A Scale",
         "Cause_change_of_strength": "Cause Change Of Strength",
         "Cause_to_amalgamate": "Cause To Amalgamate",
         "Cause_to_be_included": "Cause To Be Included",
         "Cause_to_make_progress": "Cause To Make Progress",
         "Change": "Change",
         "Change_event_time": "Change Event Time",
         "Change_of_leadership": "Change Of Leadership",
         "Change_sentiment": "Change Sentiment",
         "Change_tool": "Change Tool",
         "Check": "Check",
         "Choosing": "Choosing",
         "Collaboration": "Collaboration",
         "Come_together": "Come Together",
         "Coming_to_be": "Coming To Be",
         "Coming_to_believe": "Coming To Believe",
         "Commerce_buy": "Commerce Buy",
         "Commerce_pay": "Commerce Pay",
         "Commerce_sell": "Commerce Sell",
         "Commitment": "Commitment",
         "Committing_crime": "Committing Crime",
         "Communication": "Communication",
         "Competition": "Competition",
         "Confronting_problem": "Confronting Problem",
         "Connect": "Connect",
         "Conquering": "Conquering",
         "Containing": "Containing",
         "Control": "Control",
         "Convincing": "Convincing",
         "Cost": "Cost",
         "Create_artwork": "Create Artwork",
         "Creating": "Creating",
         "Criminal_investigation": "Criminal Investigation",
         "Cure": "Cure",
         "Damaging": "Damaging",
         "Death": "Death",
         "Deciding": "Deciding",
         "Defending": "Defending",
         "Departing": "Departing",
         "Destroying": "Destroying",
         "Dispersal": "Dispersal",
         "Earnings_and_losses": "Earnings And Losses",
         "Education_teaching": "Education Teaching",
         "Emergency": "Emergency",
         "Employment": "Employment",
         "Emptying": "Emptying",
         "Escaping": "Escaping",
         "Exchange": "Exchange",
         "Expansion": "Expansion",
         "Expend_resource": "Expend Resource",
         "Expressing_publicly": "Expressing Publicly",
         "Extradition": "Extradition",
         "Filling": "Filling",
         "Forming_relationships": "Forming Relationships",
         "GetReady": "Get Ready",
         "Getting": "Getting",
         "GiveUp": "Give Up",
         "Giving": "Giving",
         "Having_or_lacking_access": "Having Or Lacking Access",
         "Hiding_objects": "Hiding Objects",
         "Hindering": "Hindering",
         "Hold": "Hold",
         "Hostile_encounter": "Hostile Encounter",
         "Imposing_obligation": "Imposing Obligation",
         "Incident": "Incident",
         "Influence": "Influence",
         "Ingestion": "Ingestion",
         "Institutionalization": "Institutionalization",
         "Judgment_communication": "Judgment Communication",
         "Justifying": "Justifying",
         "Kidnapping": "Kidnapping",
         "Killing": "Killing",
         "Know": "Know",
         "Labeling": "Labeling",
         "Legal_rulings": "Legal Rulings",
         "Legality": "Legality",
         "Lighting": "Lighting",
         "Limiting": "Limiting",
         "Manufacturing": "Manufacturing",
         "Military_operation": "Military Operation",
         "Motion": "Motion",
         "Motion_directional": "Motion Directional",
         "Name_conferral": "Name Conferral",
         "Openness": "Openness",
         "Participation": "Participation",
         "Patrolling": "Patrolling",
         "Perception_active": "Perception Active",
         "Placing": "Placing",
         "Practice": "Practice",
         "Presence": "Presence",
         "Preserving": "Preserving",
         "Preventing_or_letting": "Preventing Or Letting",
         "Prison": "Prison",
         "Process_end": "Process End",
         "Process_start": "Process Start",
         "Protest": "Protest",
         "Publishing": "Publishing",
         "Quarreling": "Quarreling",
         "Ratification": "Ratification",
         "Receiving": "Receiving",
         "Recording": "Recording",
         "Recovering": "Recovering",
         "Reforming_a_system": "Reforming A System",
         "Releasing": "Releasing",
         "Removing": "Removing",
         "Renting": "Renting",
         "Reporting": "Reporting",
         "Request": "Request",
         "Rescuing": "Rescuing",
         "Research": "Research",
         "Resolve_problem": "Resolve Problem",
         "Response": "Response",
         "Reveal_secret": "Reveal Secret",
         "Revenge": "Revenge",
         "Rewards_and_punishments": "Rewards And Punishments",
         "Risk": "Risk",
         "Rite": "Rite",
         "Robbery": "Robbery",
         "Scouring": "Scouring",
         "Scrutiny": "Scrutiny",
         "Self_motion": "Self Motion",
         "Sending": "Sending",
         "Sign_agreement": "Sign Agreement",
         "Social_event": "Social Event",
         "Statement": "Statement",
         "Submitting_documents": "Submitting Documents",
         "Supply": "Supply",
         "Supporting": "Supporting",
         "Surrendering": "Surrendering",
         "Surrounding": "Surrounding",
         "Suspicion": "Suspicion",
         "Telling": "Telling",
         "Temporary_stay": "Temporary Stay",
         "Terrorism": "Terrorism",
         "Testing": "Testing",
         "Theft": "Theft",
         "Traveling": "Traveling",
         "Use_firearm": "Use Firearm",
         "Using": "Using",
         "Violence": "Violence",
         "Vocalizations": "Vocalizations",
         "Warning": "Warning",
         "Wearing": "Wearing",
         "Writing": "Writing", 
    }, 
    "mee-en": {
        "Business_START-ORG": "Business Start Organization", 
        "Conflict_Attack": "Conflict Attack", 
        "Conflict_Demonstrate": "Conflict Demonstrate", 
        "Contact_Meet": "Contact Meet", 
        "Contact_Phone-Write": "Contact Phone Write", 
        "Justice_Arrest-Jail": "Justice Arrest Jail", 
        "Life_Be-Born": "Life Born", 
        "Life_Die": "Life Die", 
        "Life_Divorce": "Life Divorce", 
        "Life_Injure": "Life Injure", 
        "Life_Marry": "Life Marry", 
        "Movement_Transport": "Movement Transport", 
        "Personnel_End-Position": "Personnel End Position", 
        "Personnel_Start-Position": "Personnel Start Position", 
        "Transaction_Transfer-Money": "Transaction Transfer-Money", 
        "Transaction_Transfer-Ownership": "Transaction Transfer Ownership", 
    }, 
    "rams": {
        "artifactexistence.damagedestroy.damage": "Artifact Existence Damage Destroy Damage",
        "artifactexistence.damagedestroy.destroy": "Artifact Existence Damage Destroy Destroy",
        "artifactexistence.damagedestroy.n/a": "Artifact Existence Damage Destroy",
        "conflict.attack.airstrikemissilestrike": "Conflict Attack Airstrike Missile Strike",
        "conflict.attack.biologicalchemicalpoisonattack": "Conflict Attack Biological Chemical Poison Attack",
        "conflict.attack.bombing": "Conflict Attack Bombing",
        "conflict.attack.firearmattack": "Conflict Attack Firearm Attack",
        "conflict.attack.hanging": "Conflict Attack Hanging",
        "conflict.attack.invade": "Conflict Attack Invade",
        "conflict.attack.n/a": "Conflict Attack",
        "conflict.attack.selfdirectedbattle": "Conflict Attack Self Directed Battle",
        "conflict.attack.setfire": "Conflict Attack Setfire",
        "conflict.attack.stabbing": "Conflict Attack Stabbing",
        "conflict.attack.stealrobhijack": "Conflict Attack Steal Rob Hijack",
        "conflict.attack.strangling": "Conflict Attack Strangling",
        "conflict.demonstrate.marchprotestpoliticalgathering": "Conflict Demonstrate March Protest Political Gathering",
        "conflict.demonstrate.n/a": "Conflict Demonstrate",
        "conflict.yield.n/a": "Conflict Yield",
        "conflict.yield.retreat": "Conflict Yield Retreat",
        "conflict.yield.surrender": "Conflict Yield Surrender",
        "contact.collaborate.correspondence": "Contact Collaborate Correspondence",
        "contact.collaborate.meet": "Contact Collaborate Meet",
        "contact.collaborate.n/a": "Contact Collaborate",
        "contact.commandorder.broadcast": "Contact Command Order Broadcast",
        "contact.commandorder.correspondence": "Contact Command Order Correspondence",
        "contact.commandorder.meet": "Contact Command Order Meet",
        "contact.commandorder.n/a": "Contact Command Order",
        "contact.commitmentpromiseexpressintent.broadcast": "Contact Commitment Promise Express Intent Broadcast",
        "contact.commitmentpromiseexpressintent.correspondence": "Contact Commitment Promise Express Intent Correspondence",
        "contact.commitmentpromiseexpressintent.meet": "Contact Commitment Promise Express Intent Meet",
        "contact.commitmentpromiseexpressintent.n/a": "Contact Commitment Promise Express Intent",
        "contact.discussion.correspondence": "Contact Discussion Correspondence",
        "contact.discussion.meet": "Contact Discussion Meet",
        "contact.discussion.n/a": "Contact Discussion",
        "contact.funeralvigil.meet": "Contact Funeral Vigil Meet",
        "contact.funeralvigil.n/a": "Contact Funeral Vigil",
        "contact.mediastatement.broadcast": "Contact Media Statement Broadcast",
        "contact.mediastatement.n/a": "Contact Media Statement",
        "contact.negotiate.correspondence": "Contact Negotiate Correspondence",
        "contact.negotiate.meet": "Contact Negotiate Meet",
        "contact.negotiate.n/a": "Contact Negotiate",
        "contact.prevarication.broadcast": "Contact Prevarication Broadcast",
        "contact.prevarication.correspondence": "Contact Prevarication Correspondence",
        "contact.prevarication.meet": "Contact Prevarication Meet",
        "contact.prevarication.n/a": "Contact Prevarication",
        "contact.publicstatementinperson.broadcast": "Contact Public Statement In Person Broadcast",
        "contact.publicstatementinperson.n/a": "Contact Public Statement In Person",
        "contact.requestadvise.broadcast": "Contact Request Advise Broadcast",
        "contact.requestadvise.correspondence": "Contact Request Advise Correspondence",
        "contact.requestadvise.meet": "Contact Request Advise Meet",
        "contact.requestadvise.n/a": "Contact Request Advise",
        "contact.threatencoerce.broadcast": "Contact Threaten Coerce Broadcast",
        "contact.threatencoerce.correspondence": "Contact Threaten Coerce Correspondence",
        "contact.threatencoerce.meet": "Contact Threaten Coerce Meet",
        "contact.threatencoerce.n/a": "Contact Threaten Coerce",
        "disaster.accidentcrash.accidentcrash": "Disaster Accidentcrash Accidentcrash",
        "disaster.fireexplosion.fireexplosion": "Disaster Fireexplosion Fireexplosion",
        "government.agreements.acceptagreementcontractceasefire": "Government Agreements Accept Agreement Contract Ceasefire",
        "government.agreements.n/a": "Government Agreements",
        "government.agreements.rejectnullifyagreementcontractceasefire": "Government Agreements Reject Nullify Agreement Contract Ceasefire",
        "government.agreements.violateagreement": "Government Agreements Violate Agreement",
        "government.formation.mergegpe": "Government Formation Mergegpe",
        "government.formation.n/a": "Government Formation",
        "government.formation.startgpe": "Government Formation Startpage",
        "government.legislate.legislate": "Government Legislate Legislate",
        "government.spy.spy": "Government Spy Spy",
        "government.vote.castvote": "Government Vote Castvote",
        "government.vote.n/a": "Government Vote",
        "government.vote.violationspreventvote": "Government Vote Violations Prevent Vote",
        "inspection.sensoryobserve.inspectpeopleorganization": "Inspection Sensory Observe Inspect People Organization",
        "inspection.sensoryobserve.monitorelection": "Inspection Sensory Observe Monitor Election",
        "inspection.sensoryobserve.n/a": "Inspection Sensory Observe",
        "inspection.sensoryobserve.physicalinvestigateinspect": "Inspection Sensory Observe Physical Investigate Inspect",
        "justice.arrestjaildetain.arrestjaildetain": "Justice Arrest Jail Detain",
        "justice.initiatejudicialprocess.chargeindict": "Justice Initiative Judicial Process Charge Indict",
        "justice.initiatejudicialprocess.n/a": "Justice Initiative Judicial Process",
        "justice.initiatejudicialprocess.trialhearing": "Justice Initiative Judicial Process Trial Hearing",
        "justice.investigate.investigatecrime": "Justice Investigate Investigate Crime",
        "justice.investigate.n/a": "Justice Investigate",
        "justice.judicialconsequences.convict": "Justice Judicial Consequences Convict",
        "justice.judicialconsequences.execute": "Justice Judicial Consequences Execute",
        "justice.judicialconsequences.extradite": "Justice Judicial Consequences Extradite",
        "justice.judicialconsequences.n/a": "Justice Judicial Consequences",
        "life.die.deathcausedbyviolentevents": "Life Die Death Caused By Violent Events",
        "life.die.n/a": "Life Die",
        "life.die.nonviolentdeath": "Life Die Non Violent Death",
        "life.injure.illnessdegradationhungerthirst": "Life Injure Illness Degradation Hunger Thirst",
        "life.injure.illnessdegradationphysical": "Life Injure Illness Degradation Physical",
        "life.injure.injurycausedbyviolentevents": "Life Injure Injury Caused By Violent Events",
        "life.injure.n/a": "Life Injure",
        "manufacture.artifact.build": "Manufacture Artifact Build",
        "manufacture.artifact.createintellectualproperty": "Manufacture Artifact Create Intellectual Property",
        "manufacture.artifact.createmanufacture": "Manufacture Artifact Create Manufacture",
        "manufacture.artifact.n/a": "Manufacture Artifact",
        "movement.transportartifact.bringcarryunload": "Movement Transport Artifact Bring Carry Unload",
        "movement.transportartifact.disperseseparate": "Movement Transport Artifact Disperse Separate",
        "movement.transportartifact.fall": "Movement Transport Artifact Fall",
        "movement.transportartifact.grantentry": "Movement Transport Artifact Grant Entry",
        "movement.transportartifact.hide": "Movement Transport Artifact Hide",
        "movement.transportartifact.n/a": "Movement Transport Artifact",
        "movement.transportartifact.nonviolentthrowlaunch": "Movement Transport Artifact Nonviolent Throw Launch",
        "movement.transportartifact.prevententry": "Movement Transport Artifact Prevent Entry",
        "movement.transportartifact.preventexit": "Movement Transport Artifact Prevent Exit",
        "movement.transportartifact.receiveimport": "Movement Transport Artifact Receive Import",
        "movement.transportartifact.sendsupplyexport": "Movement Transport Artifact Send Supply Export",
        "movement.transportartifact.smuggleextract": "Movement Transport Artifact Smuggle Extract",
        "movement.transportperson.bringcarryunload": "Movement Transport Person Bring Carry Unload",
        "movement.transportperson.disperseseparate": "Movement Transport Person Disperse Separate",
        "movement.transportperson.evacuationrescue": "Movement Transport Person Evacuation Rescue",
        "movement.transportperson.fall": "Movement Transport Person Fall",
        "movement.transportperson.grantentryasylum": "Movement Transport Person Grantentry Asylum",
        "movement.transportperson.hide": "Movement Transport Person Hide",
        "movement.transportperson.n/a": "Movement Transport Person",
        "movement.transportperson.prevententry": "Movement Transport Person Prevent Entry",
        "movement.transportperson.preventexit": "Movement Transport Person Prevent Exit",
        "movement.transportperson.selfmotion": "Movement Transport Person Self Motion",
        "movement.transportperson.smuggleextract": "Movement Transport Person Smuggle Extract",
        "personnel.elect.n/a": "Personnel Elect",
        "personnel.elect.winelection": "Personnel Elect Win Election",
        "personnel.endposition.firinglayoff": "Personnel End Position Firing Layoff",
        "personnel.endposition.n/a": "Personnel End Position",
        "personnel.endposition.quitretire": "Personnel End Position Quit Retire",
        "personnel.startposition.hiring": "Personnel Start Position Hiring",
        "personnel.startposition.n/a": "Personnel Start Position",
        "transaction.transaction.embargosanction": "Transaction Transaction Embargo Sanction",
        "transaction.transaction.giftgrantprovideaid": "Transaction Transaction Gift Grant Provide Aid",
        "transaction.transaction.n/a": "Transaction Transaction",
        "transaction.transaction.transfercontrol": "Transaction Transaction Transfer Control",
        "transaction.transfermoney.borrowlend": "Transaction Transfer Money Borrow Lend",
        "transaction.transfermoney.embargosanction": "Transaction Transfer Money Embargo Sanction",
        "transaction.transfermoney.giftgrantprovideaid": "Transaction Transfer Money Gift Grant Provide Aid",
        "transaction.transfermoney.n/a": "Transaction Transfer Money",
        "transaction.transfermoney.payforservice": "Transaction Transfer Money Payforservice",
        "transaction.transfermoney.purchase": "Transaction Transfer Money Purchase",
        "transaction.transferownership.borrowlend": "Transaction Transfer Ownership Borrow Lend",
        "transaction.transferownership.embargosanction": "Transaction Transfer Ownership Embargo Sanction",
        "transaction.transferownership.giftgrantprovideaid": "Transaction Transfer Ownership Gift Grant Provide Aid",
        "transaction.transferownership.n/a": "Transaction Transfer Ownership",
        "transaction.transferownership.purchase": "Transaction Transfer Ownership Purchase",  
    },
    "wikievents": {
        "ArtifactExistence.DamageDestroyDisableDismantle.Damage": "Artifact Existence Damage Destroy Disable Dismantle Damage",
        "ArtifactExistence.DamageDestroyDisableDismantle.Destroy": "Artifact Existence Damage Destroy Disable Dismantle Destroy",
        "ArtifactExistence.DamageDestroyDisableDismantle.DisableDefuse": "Artifact Existence Damage Destroy Disable Dismantle Disable Defuse",
        "ArtifactExistence.DamageDestroyDisableDismantle.Dismantle": "Artifact Existence Damage Destroy Disable Dismantle Dismantle",
        "ArtifactExistence.DamageDestroyDisableDismantle.Unspecified": "Artifact Existence Damage Destroy Disable Dismantle",
        "ArtifactExistence.ManufactureAssemble.Unspecified": "Artifact Existence Manufacture Assemble",
        "Cognitive.IdentifyCategorize.Unspecified": "Cognitive Identify Categorize",
        "Cognitive.Inspection.SensoryObserve": "Cognitive Inspection Sensory Observe",
        "Cognitive.Research.Unspecified": "Cognitive Research",
        "Cognitive.TeachingTrainingLearning.Unspecified": "Cognitive Teaching Training Learning",
        "Conflict.Attack.DetonateExplode": "Conflict Attack Detonate Explode",
        "Conflict.Attack.Unspecified": "Conflict Attack",
        "Conflict.Defeat.Unspecified": "Conflict Defeat",
        "Conflict.Demonstrate.DemonstrateWithViolence": "Conflict Demonstrate Demonstrate With Violence",
        "Conflict.Demonstrate.Unspecified": "Conflict Demonstrate",
        "Contact.Contact.Broadcast": "Contact Contact Broadcast",
        "Contact.Contact.Correspondence": "Contact Contact Correspondence",
        "Contact.Contact.Meet": "Contact Contact Meet",
        "Contact.Contact.Unspecified": "Contact Contact",
        "Contact.RequestCommand.Broadcast": "Contact Request Command Broadcast",
        "Contact.RequestCommand.Correspondence": "Contact Request Command Correspondence",
        "Contact.RequestCommand.Meet": "Contact Request Command Meet",
        "Contact.RequestCommand.Unspecified": "Contact Request Command",
        "Contact.ThreatenCoerce.Broadcast": "Contact Threaten Coerce Broadcast",
        "Contact.ThreatenCoerce.Correspondence": "Contact Threaten Coerce Correspondence",
        "Contact.ThreatenCoerce.Unspecified": "Contact Threaten Coerce",
        "Control.ImpedeInterfereWith.Unspecified": "Control Impede Interfere With",
        "Disaster.Crash.Unspecified": "Disaster Crash",
        "Disaster.DiseaseOutbreak.Unspecified": "Disaster Disease Outbreak",
        "GenericCrime.GenericCrime.GenericCrime": "Generic Crime Generic Crime Generic Crime",
        "Justice.Acquit.Unspecified": "Justice Acquit",
        "Justice.ArrestJailDetain.Unspecified": "Justice Arrest Jail Detain",
        "Justice.ChargeIndict.Unspecified": "Justice Charge Indict",
        "Justice.Convict.Unspecified": "Justice Convict",
        "Justice.InvestigateCrime.Unspecified": "Justice Investigate Crime",
        "Justice.ReleaseParole.Unspecified": "Justice Release Parole",
        "Justice.Sentence.Unspecified": "Justice Sentence",
        "Justice.TrialHearing.Unspecified": "Justice Trial Hearing",
        "Life.Die.Unspecified": "Life Die",
        "Life.Infect.Unspecified": "Life Infect",
        "Life.Injure.Unspecified": "Life Injure",
        "Medical.Intervention.Unspecified": "Medical Intervention",
        "Movement.Transportation.Evacuation": "Movement Transportation Evacuation",
        "Movement.Transportation.IllegalTransportation": "Movement Transportation Illegal Transportation",
        "Movement.Transportation.PreventPassage": "Movement Transportation Prevent Passage",
        "Movement.Transportation.Unspecified": "Movement Transportation",
        "Personnel.EndPosition.Unspecified": "Personnel End Position",
        "Personnel.StartPosition.Unspecified": "Personnel Start Position",
        "Transaction.Donation.Unspecified": "Transaction Donation",
        "Transaction.ExchangeBuySell.Unspecified": "Transaction Exchange Buy Sell",
    },
    "fewevent": {
        "Business.Collaboration": "Business Collaboration", 
        "Business.Declare-Bankruptcy": "Business Declare Bankruptcy", 
        "Business.Employment": "Business Employment", 
        "Business.Employment-Tenure": "Business Employment Tenure", 
        "Business.End-Org": "Business End Org", 
        "Business.Financing": "Business Financing", 
        "Business.Investment": "Business Investment", 
        "Business.Layoff": "Business Layoff", 
        "Business.Merge-Org": "Business Merge Org", 
        "Business.Sponsorship": "Business Sponsorship", 
        "Business.Start-Org": "Business Start Org", 
        "Business.Start-Subsidiary": "Business Start Subsidiary", 
        "Conflict.Attack": "Conflict Attack", 
        "Conflict.Demonstrate": "Conflict Demonstrate", 
        "Conflict.Riot": "Conflict Riot", 
        "Conflict.Self-Immolation": "Conflict Self Immolation", 
        "Contact.Broadcast": "Contact Broadcast", 
        "Contact.Contact": "Contact Contact", 
        "Contact.Correspondence": "Contact Correspondence", 
        "Contact.E-Mail": "Contact E Mail", 
        "Contact.Letter-Communication": "Contact Letter Communication", 
        "Contact.Meet": "Contact Meet", 
        "Contact.Online-Chat": "Contact Online Chat", 
        "Contact.Phone-Write": "Contact Phone Write", 
        "Contact.Video-Chat": "Contact Video Chat", 
        "Contact.Voice-Mail": "Contact Voice Mail", 
        "Education.Education": "Education Education", 
        "Film.Dubbing-Performance": "Film Dubbing Performance", 
        "Film.Film-Crew-Gig": "Film Film Crew Gig", 
        "Film.Film-Distribution": "Film Film Distribution", 
        "Film.Film-Festival": "Film Film Festival", 
        "Film.Film-Production": "Film Film Production", 
        "Justice.Acquit": "Justice Acquit", 
        "Justice.Appeal": "Justice Appeal", 
        "Justice.Arrest-Jail": "Justice Arrest Jail", 
        "Justice.Charge-Indict": "Justice Charge Indict", 
        "Justice.Convict": "Justice Convict", 
        "Justice.Execute": "Justice Execute", 
        "Justice.Extradite": "Justice Extradite", 
        "Justice.Fine": "Justice Fine", 
        "Justice.Pardon": "Justice Pardon", 
        "Justice.Release-Parole": "Justice Release Parole", 
        "Justice.Sentence": "Justice Sentence", 
        "Justice.Sue": "Justice Sue", 
        "Justice.Trial-Hearing": "Justice Trial Hearing", 
        "Life.Abortion": "Life Abortion", 
        "Life.Be-Born": "Life Be Born", 
        "Life.Die": "Life Die", 
        "Life.Divorce": "Life Divorce", 
        "Life.Homesick": "Life Homesick", 
        "Life.Injure": "Life Injure", 
        "Life.Marry": "Life Marry", 
        "Life.Pregnancy": "Life Pregnancy", 
        "Life.Sick": "Life Sick", 
        "Life.Travel": "Life Travel", 
        "Manufacture.Artifact": "Manufacture Artifact", 
        "Manufacture.Lean-Manufacturing": "Manufacture Lean Manufacturing", 
        "Military.Military-Command": "Military Military Command", 
        "Military.Military-Service": "Military Military Service", 
        "Military.Recruit-Training": "Military Recruit Training", 
        "Military.Recruitment": "Military Recruitment", 
        "Movement.Driving": "Movement Driving", 
        "Movement.Parking": "Movement Parking", 
        "Movement.Transport": "Movement Transport", 
        "Movement.Transport-Artifact": "Movement Transport Artifact", 
        "Movement.Transportperson": "Movement Transportperson", 
        "Music.Compose": "Music Compose", 
        "Music.Dance": "Music Dance", 
        "Music.Group-Membership": "Music Group Membership", 
        "Music.Sing": "Music Sing", 
        "Music.Track-Contribution": "Music Track Contribution", 
        "Olympics.Closing-Ceremony": "Olympics Closing Ceremony", 
        "Olympics.Olympic-Athlete-Affiliation": "Olympics Olympic Athlete Affiliation", 
        "Olympics.Olympic-Medal-Honor": "Olympics Olympic Medal Honor", 
        "Olympics.Opening-Ceremony": "Olympics Opening Ceremony", 
        "Organization.Division-Of-Labour": "Organization Division Of Labour", 
        "Organization.Leadership": "Organization Leadership", 
        "Organization.Org-Communication": "Organization Org Communication", 
        "Organization.Organization-Board-Membership": "Organization Organization Board Membership", 
        "People.Appointment": "People Appointment", 
        "People.Place-Lived": "People Place Lived", 
        "Personnel.Demotion": "Personnel Demotion", 
        "Personnel.Elect": "Personnel Elect", 
        "Personnel.End-Position": "Personnel End Position", 
        "Personnel.Nominate": "Personnel Nominate", 
        "Personnel.Performance-Appraisal": "Personnel Performance Appraisal", 
        "Personnel.Promotion": "Personnel Promotion", 
        "Personnel.Resignation": "Personnel Resignation", 
        "Personnel.Start-Position": "Personnel Start Position", 
        "Projects.Project-Participation": "Projects Project Participation", 
        "Sports.Fair-Play": "Sports Fair Play", 
        "Sports.Sports-Team-Roster": "Sports Sports Team Roster", 
        "Sports.Sports-Team-Season-Record": "Sports Sports Team Season Record", 
        "Sports.Tournament": "Sports Tournament", 
        "Transaction.Deposit": "Transaction Deposit", 
        "Transaction.Money-Laundering": "Transaction Money Laundering", 
        "Transaction.Transaction": "Transaction Transaction", 
        "Transaction.Transfer-Money": "Transaction Transfer Money", 
        "Transaction.Transfer-Ownership": "Transaction Transfer Ownership", 
        "Wine.Grape-Variety-Composition": "Wine Grape Variety Composition", 
    },
    "phee": {
        "Adverse_event": "Adverse Event",
        "Potential_therapeutic_event": "Potential Therapeutic Event", 
    },
    "casie": {
        "Attack:Databreach": "Attack Databreach",
        "Attack:Phishing": "Attack Phishing",
        "Attack:Ransom": "Attack Ransom",
        "Vulnerability-related:DiscoverVulnerability": "Vulnerability-Related Discover Vulnerability",
        "Vulnerability-related:PatchVulnerability": "Vulnerability-Related Patch Vulnerability",
    },
    "mlee": {
        "Acetylation": "Acetylation",
        "Binding": "Binding",
        "Blood_vessel_development": "Blood Vessel Development",
        "Breakdown": "Breakdown",
        "Catabolism": "Catabolism",
        "Cell_division": "Cell Division",
        "Cell_proliferation": "Cell Proliferation",
        "DNA_methylation": "DNA Methylation",
        "Death": "Death",
        "Dephosphorylation": "Dephosphorylation",
        "Development": "Development",
        "Dissociation": "Dissociation",
        "Gene_expression": "Gene Expression",
        "Growth": "Growth",
        "Localization": "Localization",
        "Metabolism": "Metabolism",
        "Negative_regulation": "Negative Regulation",
        "Pathway": "Pathway",
        "Phosphorylation": "Phosphorylation",
        "Planned_process": "Planned Process",
        "Positive_regulation": "Positive Regulation",
        "Protein_processing": "Protein Processing",
        "Regulation": "Regulation",
        "Remodeling": "Remodeling",
        "Reproduction": "Reproduction",
        "Synthesis": "Synthesis",
        "Transcription": "Transcription",
        "Translation": "Translation",
        "Ubiquitination": "Ubiquitination",
    }, 
    "genia2011": {
        "Binding": "Binding",
        "Gene_expression": "Gene Expression",
        "Localization": "Localization",
        "Negative_regulation": "Negative Regulation",
        "Phosphorylation": "Phosphorylation",
        "Positive_regulation": "Positive Regulation",
        "Protein_catabolism": "Protein Catabolism",
        "Regulation": "Regulation",
        "Transcription": "Transcription",
    },
    "genia2013": {
        "Acetylation": "Acetylation",
        "Binding": "Binding",
        "Deacetylation": "Deacetylation",
        "Gene_expression": "Gene Expression",
        "Localization": "Localization",
        "Negative_regulation": "Negative Regulation",
        "Phosphorylation": "Phosphorylation",
        "Positive_regulation": "Positive Regulation",
        "Protein_catabolism": "Protein Catabolism",
        "Protein_modification": "Protein Modification",
        "Regulation": "Regulation",
        "Transcription": "Transcription",
        "Ubiquitination": "Ubiquitination",
    },
    "speed": {
        "control": "Control", 
        "cure": "Cure", 
        "death": "Death", 
        "infect": "Infect", 
        "prevent": "Prevent", 
        "spread": "Spread", 
        "symptom": "Symptom", 
    }, 
    "muc4": {
        "Dummy": "Dummy", 
    }
}

role_type_tags = {
    "ace05-en": {
        "Person": "Person",
        "Entity": "Entity",
        "Defendant": "Defendant",
        "Prosecutor": "Prosecutor",
        "Plaintiff": "Plaintiff",
        "Buyer": "Buyer",
        "Artifact": "Artifact",
        "Seller": "Seller",
        "Destination": "Destination",
        "Origin": "Origin",
        "Vehicle": "Vehicle",
        "Agent": "Agent",
        "Attacker": "Attacker",
        "Target": "Target",
        "Victim": "Victim",
        "Instrument": "Instrument",
        "Giver": "Giver",
        "Recipient": "Recipient",
        "Org": "Organization",
        "Place": "Place",
        "Adjudicator": "Adjudicator",
        "Beneficiary": "Beneficiary",
    },
    "richere-en": {
        "Agent": "Agent", 
        "Org": "Organization", 
        "Place": "Place", 
        "Target": "Target", 
        "Instrument": "Instrument", 
        "Place": "Place", 
        "Entity": "Entity", 
        "Audience": "Audience", 
        "Person": "Person", 
        "Defendant": "Defendant", 
        "Prosecutor": "Prosecutor", 
        "Adjudicator": "Adjudicator",
        "Plaintiff": "Plaintiff", 
        "Destination": "Destination", 
        "Origin": "Origin", 
        "Victim": "Victim", 
        "Artifact": "Artifact", 
        "Beneficiary": "Beneficiary", 
        "Giver": "Giver", 
        "Recipient": "Recipient", 
        "Attacker": "Attacker", 
        "Thing": "Thing", 
    },
    "m2e2": {
        "Person": "Person",
        "Entity": "Entity",
        "Destination": "Destination",
        "Origin": "Origin",
        "Vehicle": "Vehicle",
        "Agent": "Agent",
        "Attacker": "Attacker",
        "Target": "Target",
        "Victim": "Victim",
        "Instrument": "Instrument",
        "Giver": "Giver",
        "Recipient": "Recipient",
        "Place": "Place",
        "Police": "Police",
        "Artifact": "Artifact", 
    },
    "geneva": {
        "Act": "Act",
        "Action": "Action",
        "Activity": "Activity",
        "Actor": "Actor",
        "Addressee": "Addressee",
        "Affected": "Affected",
        "Affliction": "Affliction",
        "Agent": "Agent",
        "Agreement": "Agreement",
        "Area": "Area",
        "Arguer": "Arguer",
        "Arguer2": "Arguer2",
        "Arguers": "Arguers",
        "Assailant": "Assailant",
        "Asset": "Asset",
        "Attendees": "Attendees",
        "Attribute": "Attribute",
        "Author": "Author",
        "Authorities": "Authorities",
        "Avenger": "Avenger",
        "Barrier": "Barrier",
        "Behavior": "Behavior",
        "Beneficiary": "Beneficiary",
        "Benefited_party": "Benefited Party",
        "Body": "Body",
        "Body_location": "Body Location",
        "Body_part": "Body Part",
        "Buyer": "Buyer",
        "Carrier": "Carrier",
        "Cause": "Cause",
        "Charges": "Charges",
        "Chosen": "Chosen",
        "Circumstances": "Circumstances",
        "Clothing": "Clothing",
        "Cognizer": "Cognizer",
        "Communicator": "Communicator",
        "Competition": "Competition",
        "Components": "Components",
        "Configuration": "Configuration",
        "Conqueror": "Conqueror",
        "Container": "Container",
        "Content": "Content",
        "Contents": "Contents",
        "Controlling_variable": "Controlling Variable",
        "Course": "Course",
        "Created_entity": "Created Entity",
        "Creator": "Creator",
        "Crime": "Crime",
        "Culture": "Culture",
        "Deceased": "Deceased",
        "Decision": "Decision",
        "Defender": "Defender",
        "Dependent_variable": "Dependent Variable",
        "Destroyer": "Destroyer",
        "Difference": "Difference",
        "Dimension": "Dimension",
        "Direction": "Direction",
        "Distance": "Distance",
        "Domain": "Domain",
        "Donor": "Donor",
        "Duration": "Duration",
        "Earner": "Earner",
        "Earnings": "Earnings",
        "Effect": "Effect",
        "Employee": "Employee",
        "Employer": "Employer",
        "Entity": "Entity",
        "Evaluee": "Evaluee",
        "Event": "Event",
        "Evidence": "Evidence",
        "Exchanger_1": "Exchanger 1",
        "Exchanger_2": "Exchanger 2",
        "Exchangers": "Exchangers",
        "Experiencer": "Experiencer",
        "Fact": "Fact",
        "Factory": "Factory",
        "Field": "Field",
        "Figures": "Figures",
        "Final_category": "Final Category",
        "Final_quality": "Final Quality",
        "Final_subevent": "Final Subevent",
        "Final_value": "Final Value",
        "Focal_entity": "Focal Entity",
        "Goal": "Goal",
        "Goal_area": "Goal Area",
        "Goods": "Goods",
        "Ground": "Ground",
        "Group": "Group",
        "Helper": "Helper",
        "Hindrance": "Hindrance",
        "Host": "Host",
        "Imposed_purpose": "Imposed Purpose",
        "Incident": "Incident",
        "Individuals": "Individuals",
        "Information": "Information",
        "Ingestibles": "Ingestibles",
        "Ingestor": "Ingestor",
        "Inherent_purpose": "Inherent Purpose",
        "Initial_category": "Initial Category",
        "Initial_size": "Initial Size",
        "Initial_subevent": "Initial Subevent",
        "Injured_party": "Injured Party",
        "Injury": "Injury",
        "Inspector": "Inspector",
        "Instrument": "Instrument",
        "Intended_event": "Intended Event",
        "Interlocutors": "Interlocutors",
        "Investigator": "Investigator",
        "Issue": "Issue",
        "Item": "Item",
        "Killer": "Killer",
        "Label": "Label",
        "Location": "Location",
        "Manipulator": "Manipulator",
        "Manner": "Manner",
        "Means": "Means",
        "Medication": "Medication",
        "Medium": "Medium",
        "Member": "Member",
        "Message": "Message",
        "Money": "Money",
        "New_leader": "New Leader",
        "New_member": "New Member",
        "Object": "Object",
        "Occasion": "Occasion",
        "Offender": "Offender",
        "Offense": "Offense",
        "Offerer": "Offerer",
        "Old_leader": "Old Leader",
        "Old_order": "Old Order",
        "Part_1": "Part 1",
        "Part_2": "Part 2",
        "Participants": "Participants",
        "Partners": "Partners",
        "Parts": "Parts",
        "Path": "Path",
        "Patient": "Patient",
        "Payer": "Payer",
        "Perceiver_agentive": "Perceiver Agentive",
        "Perpetrator": "Perpetrator",
        "Phenomenon": "Phenomenon",
        "Place": "Place",
        "Place_of_employment": "Place Of Employment",
        "Position": "Position",
        "Possibilities": "Possibilities",
        "Potential_hindrance": "Potential Hindrance",
        "Problem": "Problem",
        "Process": "Process",
        "Producer": "Producer",
        "Product": "Product",
        "Project": "Project",
        "Proposal": "Proposal",
        "Proposed_action": "Proposed Action",
        "Protagonist": "Protagonist",
        "Punishment": "Punishment",
        "Purpose": "Purpose",
        "Rate": "Rate",
        "Ratifier": "Ratifier",
        "Reason": "Reason",
        "Recipient": "Recipient",
        "Researcher": "Researcher",
        "Resource": "Resource",
        "Responding_entity": "Responding Entity",
        "Response": "Response",
        "Result": "Result",
        "Result_size": "Result Size",
        "Role": "Role",
        "Selector": "Selector",
        "Self_mover": "Self Mover",
        "Seller": "Seller",
        "Sender": "Sender",
        "Side_1": "Side 1",
        "Side_2": "Side 2",
        "Sides": "Sides",
        "Signatory": "Signatory",
        "Situation": "Situation",
        "Skill": "Skill",
        "Social_event": "Social Event",
        "Source": "Source",
        "Speaker": "Speaker",
        "Specified_entity": "Specified Entity",
        "Speed": "Speed",
        "State": "State",
        "Student": "Student",
        "Subject": "Subject",
        "Supplier": "Supplier",
        "Supported": "Supported",
        "Supporter": "Supporter",
        "Suspect": "Suspect",
        "Task": "Task",
        "Teacher": "Teacher",
        "Terrorist": "Terrorist",
        "Tested_property": "Tested Property",
        "Tester": "Tester",
        "Text": "Text",
        "Theme": "Theme",
        "Theme_1": "Theme 1",
        "Theme_2": "Theme 2",
        "Themes": "Themes",
        "Time": "Time",
        "Topic": "Topic",
        "Transferors": "Transferors",
        "Traveler": "Traveler",
        "Traveller": "Traveller",
        "Treatment": "Treatment",
        "Trigger": "Trigger",
        "Type": "Type",
        "Unconfirmed_content": "Unconfirmed Content",
        "Undertaking": "Undertaking",
        "Undesirable_event": "Undesirable Event",
        "Unwanted_entity": "Unwanted Entity",
        "Useful_location": "Useful Location",
        "Value_1": "Value 1",
        "Value_2": "Value 2",
        "Vehicle": "Vehicle",
        "Venue": "Venue",
        "Victim": "Victim",
        "Weapon": "Weapon",
        "Wearer": "Wearer",
        "Whole": "Whole",
    },
    "mee-en": {
        "Agent": "Agent",
        "Artifact": "Artifact",
        "Attacker": "Attacker",
        "Beneficiary": "Beneficiary",
        "Buyer": "Buyer",
        "Crime": "Crime",
        "Destination": "Destination",
        "Entity": "Entity",
        "Instrument": "Instrument",
        "Money": "Money",
        "Giver": "Giver",
        "Organization": "Organization",
        "Origin": "Origin",
        "Person": "Person",
        "Place": "Place",
        "Position": "Position",
        "Price": "Price",
        "Recipient": "Recipient",
        "Seller": "Seller",
        "Target": "Target",
        "Time": "Time",
        "Vehicle": "Vehicle",
        "Victim": "Victim",
    },
    "rams": {
        "artifact": "Artifact",
        "artifactmoney": "Artifact Money",
        "attacker": "Attacker",
        "ballot": "Ballot",
        "beneficiary": "Beneficiary",
        "candidate": "Candidate",
        "communicator": "Communicator",
        "crashobject": "Crash Object",
        "crime": "Crime",
        "damager": "Damager",
        "damagerdestroyer": "Damager Destroyer",
        "deceased": "Deceased",
        "defendant": "Defendant",
        "demonstrator": "Demonstrator",
        "destination": "Destination",
        "destroyer": "Destroyer",
        "detainee": "Detainee",
        "driverpassenger": "Driver Passenger",
        "employee": "Employee",
        "executioner": "Executioner",
        "extraditer": "Extraditer",
        "fireexplosionobject": "Fire Explosion Object",
        "founder": "Founder",
        "giver": "Giver",
        "governmentbody": "Government Body",
        "gpe": "Gpe",
        "granter": "Granter",
        "hidingplace": "Hiding Place",
        "injurer": "Injurer",
        "inspectedentity": "Inspected Entity",
        "inspector": "Inspector",
        "instrument": "Instrument",
        "investigator": "Investigator",
        "jailer": "Jailer",
        "judgecourt": "Judge Court",
        "killer": "Killer",
        "law": "Law",
        "manufacturer": "Manufacturer",
        "money": "Money",
        "monitor": "Monitor",
        "monitoredentity": "Monitored Entity",
        "observedentity": "Observed Entity",
        "observer": "Observer",
        "origin": "Origin",
        "otherparticipant": "Other Participant",
        "participant": "Participant",
        "passenger": "Passenger",
        "place": "Place",
        "placeofemployment": "Place Of Employment",
        "preventer": "Preventer",
        "prosecutor": "Prosecutor",
        "recipient": "Recipient",
        "rejecternullifier": "Rejecter Nullifier",
        "result": "Result",
        "retreater": "Retreater",
        "spy": "Spy",
        "surrenderer": "Surrenderer",
        "target": "Target",
        "territoryorfacility": "Territoryor Facility",
        "transporter": "Transporter",
        "vehicle": "Vehicle",
        "victim": "Victim",
        "violator": "Violator",
        "voter": "Voter",
        "yielder": "Yielder",  
    },
    "wikievents": {
        "AcquiredEntity": "Acquired Entity",
        "Artifact": "Artifact",
        "ArtifactMoney": "Artifact Money",
        "Attacker": "Attacker",
        "BodyPart": "Body Part",
        "Communicator": "Communicator",
        "Components": "Components",
        "CrashObject": "Crash Object",
        "Damager": "Damager",
        "DamagerDestroyer": "Damager Destroyer",
        "Defeated": "Defeated",
        "Defendant": "Defendant",
        "Demonstrator": "Demonstrator",
        "Destination": "Destination",
        "Destroyer": "Destroyer",
        "Detainee": "Detainee",
        "Disabler": "Disabler",
        "Dismantler": "Dismantler",
        "Employee": "Employee",
        "ExplosiveDevice": "Explosive Device",
        "Giver": "Giver",
        "IdentifiedObject": "Identified Object",
        "IdentifiedRole": "Identified Role",
        "Identifier": "Identifier",
        "Impeder": "Impeder",
        "Injurer": "Injurer",
        "Instrument": "Instrument",
        "Investigator": "Investigator",
        "Jailer": "Jailer",
        "JudgeCourt": "Judge Court",
        "Killer": "Killer",
        "Learner": "Learner",
        "ManufacturerAssembler": "Manufacturer Assembler",
        "ObservedEntity": "Observed Entity",
        "Observer": "Observer",
        "Origin": "Origin",
        "Participant": "Participant",
        "PassengerArtifact": "Passenger Artifact",
        "Patient": "Patient",
        "PaymentBarter": "Payment Barter",
        "Perpetrator": "Perpetrator",
        "Place": "Place",
        "PlaceOfEmployment": "Place Of Employment",
        "Position": "Position",
        "Preventer": "Preventer",
        "Prosecutor": "Prosecutor",
        "Recipient": "Recipient",
        "Regulator": "Regulator",
        "Researcher": "Researcher",
        "Subject": "Subject",
        "Target": "Target",
        "TeacherTrainer": "Teacher Trainer",
        "Topic": "Topic",
        "Transporter": "Transporter",
        "Treater": "Treater",
        "Vehicle": "Vehicle",
        "Victim": "Victim",
        "Victor": "Victor",
    },
    "phee": {
        "Combination_Drug": "Combination Drug",
        "Effect": "Effect",
        "Subject": "Subject",
        "Subject_Age": "Subject Age",
        "Subject_Disorder": "Subject Disorder",
        "Subject_Gender": "Subject Gender",
        "Subject_Population": "Subject Population",
        "Subject_Race": "Subject Race",
        "Treatment": "Treatment",
        "Treatment_Disorder": "Treatment Disorder",
        "Treatment_Dosage": "Treatment Dosage",
        "Treatment_Drug": "Treatment Drug",
        "Treatment_Duration": "Treatment Duration",
        "Treatment_Freq": "Treatment Freq",
        "Treatment_Route": "Treatment Route",
        "Treatment_Time_elapsed": "Treatment Time Elapsed",
    },
    "casie": {
        "Attack-Pattern": "Attack Pattern",
        "Attacker": "Attacker",
        "CVE": "CVE",
        "Capabilities": "Capabilities",
        "Compromised-Data": "Compromised Data",
        "Damage-Amount": "Damage Amount",
        "Discoverer": "Discoverer",
        "Issues-Addressed": "Issues Addressed",
        "Number-of-Data": "Number of Data",
        "Number-of-Victim": "Number of Victim",
        "Patch": "Patch",
        "Patch-Number": "Patch Number",
        "Payment-Method": "Payment Method",
        "Place": "Place",
        "Price": "Price",
        "Purpose": "Purpose",
        "Releaser": "Releaser",
        "Supported_Platform": "Supported Platform",
        "Time": "Time",
        "Tool": "Tool",
        "Trusted-Entity": "Trusted Entity",
        "Victim": "Victim",
        "Vulnerability": "Vulnerability",
        "Vulnerable_System": "Vulnerable System",
        "Vulnerable_System_Owner": "Vulnerable System Owner",
        "Vulnerable_System_Version": "Vulnerable System Version",
    },
    "mlee": {
        "AtLoc": "At Loc",
        "CSite": "CSite",
        "Cause": "Cause",
        "FromLoc": "From Loc",
        "Instrument": "Instrument",
        "Instrument2": "Instrument 2",
        "Participant": "Participant",
        "Participant2": "Participant 2",
        "Participant3": "Participant 3",
        "Participant4": "Participant 4",
        "Site": "Site",
        "Theme": "Theme",
        "Theme2": "Theme 2",
        "ToLoc": "To Loc",
    },
    "genia2011": {
        "AtLoc": "At Loc",
        "CSite": "CSite",
        "Cause": "Cause",
        "Site": "Site",
        "Site2": "Site 2",
        "Theme": "Theme",
        "Theme2": "Theme 2",
        "Theme3": "Theme 3",
        "Theme4": "Theme 4",
        "ToLoc": "To Loc",
    },
    "genia2013": {
        "CSite": "CSite",
        "Cause": "Cause",
        "Site": "Site",
        "Site2": "Site 2",
        "Theme": "Theme",
        "Theme2": "Theme 2",
        "ToLoc": "To Loc",
    },
    "muc4": {
        "PerpInd": "Person",
        "PerpOrg": "Organization", 
        "Target": "Target",
        "Victim": "Victim", 
        "Weapon": "Weapon",
    }, 
}
