event_type_tags = {
    "ace05-en": {
        "Business:Declare-Bankruptcy": "Business Declare Bankruptcy", 
        "Business:End-Org": "Business End Organization", 
        "Business:Merge-Org": "Business Merge Organization", 
        "Business:Start-Org": "Business Start Organization", 
        "Conflict:Attack": "Conflict Attack", 
        "Conflict:Demonstrate": "Conflict Demonstrate", 
        "Contact:Meet": "Contact Meet", 
        "Contact:Phone-Write": "Contact Phone Write", 
        "Justice:Acquit": "Justice Acquit", 
        "Justice:Appeal": "Justice Appeal", 
        "Justice:Arrest-Jail": "Justice Arrest Jail", 
        "Justice:Charge-Indict": "Justice Charge Indict", 
        "Justice:Convict": "Justice Convict", 
        "Justice:Execute": "Justice Execute", 
        "Justice:Extradite": "Justice Extradite", 
        "Justice:Fine": "Justice Fine", 
        "Justice:Pardon": "Justice Pardon", 
        "Justice:Release-Parole": "Justice Release Parole", 
        "Justice:Sentence": "Justice Sentence", 
        "Justice:Sue": "Justice Sue", 
        "Justice:Trial-Hearing": "Justice Trial Hearing", 
        "Life:Be-Born": "Life Born", 
        "Life:Die": "Life Die", 
        "Life:Divorce": "Life Divorce", 
        "Life:Injure": "Life Injure", 
        "Life:Marry": "Life Marry", 
        "Movement:Transport": "Movement Transport", 
        "Personnel:Elect": "Personnel Elect", 
        "Personnel:End-Position": "Personnel End Position", 
        "Personnel:Nominate": "Personnel Nominate", 
        "Personnel:Start-Position": "Personnel Start-Position", 
        "Transaction:Transfer-Money": "Transaction Transfer Money", 
        "Transaction:Transfer-Ownership": "Transaction Transfer Ownership", 
    }, 
    "richere-en": {
        "Business:Start-Org": "Business Start Organization", 
        "Business:Merge-Org": "Business Merge Organization", 
        "Business:End-Org": "Business End Organization", 
        "Business:Declare-Bankruptcy": "Business Declare Bankruptcy", 
        "Conflict:Attack": "Conflict Attack", 
        "Conflict:Demonstrate": "Conflict Demonstrate", 
        "Contact:Meet": "Contact Meet", 
        "Contact:Correspondence": "Contact Correspondence", 
        "Contact:Broadcast": "Contact Broadcast", 
        "Contact:Contact": "Contact Contact", 
        "Justice:Arrest-Jail": "Justice Arrest Jail", 
        "Justice:Release-Parole": "Justice Release Parole", 
        "Justice:Trial-Hearing": "Justice Trial Hearing", 
        "Justice:Charge-Indict": "Justice Charge Indict", 
        "Justice:Sue": "Justice Sue", 
        "Justice:Convict": "Justice Convict", 
        "Justice:Appeal": "Justice Appeal", 
        "Justice:Sentence": "Justice Sentence", 
        "Justice:Fine": "Justice Fine", 
        "Justice:Execute": "Justice Execute", 
        "Justice:Extradite": "Justice Extradite", 
        "Justice:Acquit": "Justice Acquit", 
        "Justice:Pardon": "Justice Pardon", 
        "Life:Be-Born": "Life Born", 
        "Life:Marry": "Life Marry", 
        "Life:Divorce": "Life Divorce", 
        "Life:Injure": "Life Injure", 
        "Life:Die": "Life Die", 
        "Movement:Transport-Person": "Movement Transport Person", 
        "Movement:Transport-Artifact": "Movement Transport Artifact", 
        "Manufacture:Artifact": "Manufacture Artifact", 
        "Personnel:Start-Position": "Personnel Start Position", 
        "Personnel:End-Position": "Personnel End Position", 
        "Personnel:Nominate": "Personnel Nominate", 
        "Personnel:Elect": "Personnel Elect", 
        "Transaction:Transfer-Ownership": "Transaction Transfer Ownership", 
        "Transaction:Transfer-Money": "Transaction Transfer Money", 
        "Transaction:Transaction": "Transaction Transaction", 
    }, 
    "m2e2": {
        "Conflict:Attack": "Conflict Attack", 
        "Conflict:Demonstrate": "Conflict Demonstrate", 
        "Contact:Meet": "Contact Meet", 
        "Contact:Phone-Write": "Contact Phone Write", 
        "Justice:Arrest-Jail": "Justice Arrest Jail", 
        "Life:Die": "Life Die", 
        "Movement:Transport": "Movement Transport", 
        "Transaction:Transfer-Money": "Transaction Transfer Money", 
    }, 
    "geneva": {
        "Achieve": "Achieve",
        "Action": "Action",
        "Adducing": "Adducing",
        "Agree_or_refuse_to_act": "Agree Refuse Act",
        "Arranging": "Arranging",
        "Arrest": "Arrest",
        "Arriving": "Arriving",
        "Assistance": "Assistance",
        "Attack": "Attack",
        "Bearing_arms": "Bearing Arms",
        "Becoming": "Becoming",
        "Becoming_a_member": "Becoming A Member",
        "Bodily_harm": "Bodily Harm",
        "Bringing": "Bringing",
        "Building": "Building",
        "Catastrophe": "Catastrophe",
        "Causation": "Causation",
        "Cause_change_of_position_on_a_scale": "Cause Change Position on Acale",
        "Cause_to_amalgamate": "Cause Amalgamate",
        "Cause_to_make_progress": "Cause Make Progress",
        "Change": "Change",
        "Change_of_leadership": "Change Leadership",
        "Check": "Check",
        "Choosing": "Choosing",
        "Collaboration": "Collaboration",
        "Come_together": "Come Together",
        "Coming_to_be": "Coming",
        "Coming_to_believe": "Coming Believe",
        "Commerce_buy": "Commerce Buy",
        "Commerce_pay": "Commerce Pay",
        "Commerce_sell": "Commerce Sell",
        "Commitment": "Commitment",
        "Committing_crime": "Committing Crime",
        "Communication": "Communication",
        "Competition": "Competition",
        "Confronting_problem": "Confronting Problem",
        "Connect": "Connect",
        "Conquering": "Conquering",
        "Containing": "Containing",
        "Control": "Control",
        "Convincing": "Convincing",
        "Cost": "Cost",
        "Create_artwork": "Create Artwork",
        "Creating": "Creating",
        "Criminal_investigation": "Criminal Investigation",
        "Cure": "Cure",
        "Damaging": "Damaging",
        "Death": "Death",
        "Deciding": "Deciding",
        "Defending": "Defending",
        "Departing": "Departing",
        "Destroying": "Destroying",
        "Dispersal": "Dispersal",
        "Earnings_and_losses": "Earnings Losses",
        "Education_teaching": "Education Teaching",
        "Emergency": "Emergency",
        "Employment": "Employment",
        "Emptying": "Emptying",
        "Exchange": "Exchange",
        "Expansion": "Expansion",
        "Filling": "Filling",
        "GetReady": "Get Ready",
        "Getting": "Getting",
        "Giving": "Giving",
        "Hindering": "Hindering",
        "Hold": "Hold",
        "Hostile_encounter": "Hostile Encounter",
        "Influence": "Influence",
        "Ingestion": "Ingestion",
        "Judgment_communication": "Judgment Communication",
        "Killing": "Killing",
        "Know": "Know",
        "Labeling": "Labeling",
        "Legality": "Legality",
        "Manufacturing": "Manufacturing",
        "Motion": "Motion",
        "Motion_directional": "Motion Directional",
        "Openness": "Openness",
        "Participation": "Participation",
        "Perception_active": "Perception Active",
        "Placing": "Placing",
        "Practice": "Practice",
        "Presence": "Presence",
        "Preventing_or_letting": "Preventing Letting",
        "Process_end": "Process End",
        "Process_start": "Process Start",
        "Protest": "Protest",
        "Quarreling": "Quarreling",
        "Ratification": "Ratification",
        "Receiving": "Receiving",
        "Recovering": "Recovering",
        "Removing": "Removing",
        "Request": "Request",
        "Research": "Research",
        "Resolve_problem": "Resolve Problem",
        "Response": "Response",
        "Reveal_secret": "Reveal Secret",
        "Revenge": "Revenge",
        "Rite": "Rite",
        "Scrutiny": "Scrutiny",
        "Self_motion": "Self Motion",
        "Sending": "Sending",
        "Sign_agreement": "Sign Agreement",
        "Social_event": "Social Event",
        "Statement": "Statement",
        "Supply": "Supply",
        "Supporting": "Supporting",
        "Telling": "Telling",
        "Terrorism": "Terrorism",
        "Testing": "Testing",
        "Theft": "Theft",
        "Traveling": "Traveling",
        "Using": "Using",
        "Wearing": "Wearing",
        "Writing": "Writing",
    }, 
    "maven": {
         "Achieve": "Achieve",
         "Action": "Action",
         "Adducing": "Adducing",
         "Agree_or_refuse_to_act": "Agree Or Refuse To Act",
         "Aiming": "Aiming",
         "Arranging": "Arranging",
         "Arrest": "Arrest",
         "Arriving": "Arriving",
         "Assistance": "Assistance",
         "Attack": "Attack",
         "Award": "Award",
         "Bearing_arms": "Bearing Arms",
         "Becoming": "Becoming",
         "Becoming_a_member": "Becoming A Member",
         "Being_in_operation": "Being In Operation",
         "Besieging": "Besieging",
         "Bodily_harm": "Bodily Harm",
         "Body_movement": "Body Movement",
         "Breathing": "Breathing",
         "Bringing": "Bringing",
         "Building": "Building",
         "Carry_goods": "Carry Goods",
         "Catastrophe": "Catastrophe",
         "Causation": "Causation",
         "Cause_change_of_position_on_a_scale": "Cause Change Of Position On A Scale",
         "Cause_change_of_strength": "Cause Change Of Strength",
         "Cause_to_amalgamate": "Cause To Amalgamate",
         "Cause_to_be_included": "Cause To Be Included",
         "Cause_to_make_progress": "Cause To Make Progress",
         "Change": "Change",
         "Change_event_time": "Change Event Time",
         "Change_of_leadership": "Change Of Leadership",
         "Change_sentiment": "Change Sentiment",
         "Change_tool": "Change Tool",
         "Check": "Check",
         "Choosing": "Choosing",
         "Collaboration": "Collaboration",
         "Come_together": "Come Together",
         "Coming_to_be": "Coming To Be",
         "Coming_to_believe": "Coming To Believe",
         "Commerce_buy": "Commerce Buy",
         "Commerce_pay": "Commerce Pay",
         "Commerce_sell": "Commerce Sell",
         "Commitment": "Commitment",
         "Committing_crime": "Committing Crime",
         "Communication": "Communication",
         "Competition": "Competition",
         "Confronting_problem": "Confronting Problem",
         "Connect": "Connect",
         "Conquering": "Conquering",
         "Containing": "Containing",
         "Control": "Control",
         "Convincing": "Convincing",
         "Cost": "Cost",
         "Create_artwork": "Create Artwork",
         "Creating": "Creating",
         "Criminal_investigation": "Criminal Investigation",
         "Cure": "Cure",
         "Damaging": "Damaging",
         "Death": "Death",
         "Deciding": "Deciding",
         "Defending": "Defending",
         "Departing": "Departing",
         "Destroying": "Destroying",
         "Dispersal": "Dispersal",
         "Earnings_and_losses": "Earnings And Losses",
         "Education_teaching": "Education Teaching",
         "Emergency": "Emergency",
         "Employment": "Employment",
         "Emptying": "Emptying",
         "Escaping": "Escaping",
         "Exchange": "Exchange",
         "Expansion": "Expansion",
         "Expend_resource": "Expend Resource",
         "Expressing_publicly": "Expressing Publicly",
         "Extradition": "Extradition",
         "Filling": "Filling",
         "Forming_relationships": "Forming Relationships",
         "GetReady": "Get Ready",
         "Getting": "Getting",
         "GiveUp": "Give Up",
         "Giving": "Giving",
         "Having_or_lacking_access": "Having Or Lacking Access",
         "Hiding_objects": "Hiding Objects",
         "Hindering": "Hindering",
         "Hold": "Hold",
         "Hostile_encounter": "Hostile Encounter",
         "Imposing_obligation": "Imposing Obligation",
         "Incident": "Incident",
         "Influence": "Influence",
         "Ingestion": "Ingestion",
         "Institutionalization": "Institutionalization",
         "Judgment_communication": "Judgment Communication",
         "Justifying": "Justifying",
         "Kidnapping": "Kidnapping",
         "Killing": "Killing",
         "Know": "Know",
         "Labeling": "Labeling",
         "Legal_rulings": "Legal Rulings",
         "Legality": "Legality",
         "Lighting": "Lighting",
         "Limiting": "Limiting",
         "Manufacturing": "Manufacturing",
         "Military_operation": "Military Operation",
         "Motion": "Motion",
         "Motion_directional": "Motion Directional",
         "Name_conferral": "Name Conferral",
         "Openness": "Openness",
         "Participation": "Participation",
         "Patrolling": "Patrolling",
         "Perception_active": "Perception Active",
         "Placing": "Placing",
         "Practice": "Practice",
         "Presence": "Presence",
         "Preserving": "Preserving",
         "Preventing_or_letting": "Preventing Or Letting",
         "Prison": "Prison",
         "Process_end": "Process End",
         "Process_start": "Process Start",
         "Protest": "Protest",
         "Publishing": "Publishing",
         "Quarreling": "Quarreling",
         "Ratification": "Ratification",
         "Receiving": "Receiving",
         "Recording": "Recording",
         "Recovering": "Recovering",
         "Reforming_a_system": "Reforming A System",
         "Releasing": "Releasing",
         "Removing": "Removing",
         "Renting": "Renting",
         "Reporting": "Reporting",
         "Request": "Request",
         "Rescuing": "Rescuing",
         "Research": "Research",
         "Resolve_problem": "Resolve Problem",
         "Response": "Response",
         "Reveal_secret": "Reveal Secret",
         "Revenge": "Revenge",
         "Rewards_and_punishments": "Rewards And Punishments",
         "Risk": "Risk",
         "Rite": "Rite",
         "Robbery": "Robbery",
         "Scouring": "Scouring",
         "Scrutiny": "Scrutiny",
         "Self_motion": "Self Motion",
         "Sending": "Sending",
         "Sign_agreement": "Sign Agreement",
         "Social_event": "Social Event",
         "Statement": "Statement",
         "Submitting_documents": "Submitting Documents",
         "Supply": "Supply",
         "Supporting": "Supporting",
         "Surrendering": "Surrendering",
         "Surrounding": "Surrounding",
         "Suspicion": "Suspicion",
         "Telling": "Telling",
         "Temporary_stay": "Temporary Stay",
         "Terrorism": "Terrorism",
         "Testing": "Testing",
         "Theft": "Theft",
         "Traveling": "Traveling",
         "Use_firearm": "Use Firearm",
         "Using": "Using",
         "Violence": "Violence",
         "Vocalizations": "Vocalizations",
         "Warning": "Warning",
         "Wearing": "Wearing",
         "Writing": "Writing", 
    }, 
    "mee-en": {
        "Business_START-ORG": "Business Start Organization", 
        "Conflict_Attack": "Conflict Attack", 
        "Conflict_Demonstrate": "Conflict Demonstrate", 
        "Contact_Meet": "Contact Meet", 
        "Contact_Phone-Write": "Contact Phone Write", 
        "Justice_Arrest-Jail": "Justice Arrest Jail", 
        "Life_Be-Born": "Life Born", 
        "Life_Die": "Life Die", 
        "Life_Divorce": "Life Divorce", 
        "Life_Injure": "Life Injure", 
        "Life_Marry": "Life Marry", 
        "Movement_Transport": "Movement Transport", 
        "Personnel_End-Position": "Personnel End Position", 
        "Personnel_Start-Position": "Personnel Start Position", 
        "Transaction_Transfer-Money": "Transaction Transfer-Money", 
        "Transaction_Transfer-Ownership": "Transaction Transfer Ownership", 
    }, 
    "rams": {
        "artifactexistence.damagedestroy.damage": "Artifact Existence Damage Destroy Damage",
        "artifactexistence.damagedestroy.destroy": "Artifact Existence Damage Destroy Destroy",
        "artifactexistence.damagedestroy.n/a": "Artifact Existence Damage Destroy",
        "conflict.attack.airstrikemissilestrike": "Conflict Attack Airstrike Missile Strike",
        "conflict.attack.biologicalchemicalpoisonattack": "Conflict Attack Biological Chemical Poison Attack",
        "conflict.attack.bombing": "Conflict Attack Bombing",
        "conflict.attack.firearmattack": "Conflict Attack Firearm Attack",
        "conflict.attack.hanging": "Conflict Attack Hanging",
        "conflict.attack.invade": "Conflict Attack Invade",
        "conflict.attack.n/a": "Conflict Attack",
        "conflict.attack.selfdirectedbattle": "Conflict Attack Self Directed Battle",
        "conflict.attack.setfire": "Conflict Attack Setfire",
        "conflict.attack.stabbing": "Conflict Attack Stabbing",
        "conflict.attack.stealrobhijack": "Conflict Attack Steal Rob Hijack",
        "conflict.attack.strangling": "Conflict Attack Strangling",
        "conflict.demonstrate.marchprotestpoliticalgathering": "Conflict Demonstrate March Protest Political Gathering",
        "conflict.demonstrate.n/a": "Conflict Demonstrate",
        "conflict.yield.n/a": "Conflict Yield",
        "conflict.yield.retreat": "Conflict Yield Retreat",
        "conflict.yield.surrender": "Conflict Yield Surrender",
        "contact.collaborate.correspondence": "Contact Collaborate Correspondence",
        "contact.collaborate.meet": "Contact Collaborate Meet",
        "contact.collaborate.n/a": "Contact Collaborate",
        "contact.commandorder.broadcast": "Contact Command Order Broadcast",
        "contact.commandorder.correspondence": "Contact Command Order Correspondence",
        "contact.commandorder.meet": "Contact Command Order Meet",
        "contact.commandorder.n/a": "Contact Command Order",
        "contact.commitmentpromiseexpressintent.broadcast": "Contact Commitment Promise Express Intent Broadcast",
        "contact.commitmentpromiseexpressintent.correspondence": "Contact Commitment Promise Express Intent Correspondence",
        "contact.commitmentpromiseexpressintent.meet": "Contact Commitment Promise Express Intent Meet",
        "contact.commitmentpromiseexpressintent.n/a": "Contact Commitment Promise Express Intent",
        "contact.discussion.correspondence": "Contact Discussion Correspondence",
        "contact.discussion.meet": "Contact Discussion Meet",
        "contact.discussion.n/a": "Contact Discussion",
        "contact.funeralvigil.meet": "Contact Funeral Vigil Meet",
        "contact.funeralvigil.n/a": "Contact Funeral Vigil",
        "contact.mediastatement.broadcast": "Contact Media Statement Broadcast",
        "contact.mediastatement.n/a": "Contact Media Statement",
        "contact.negotiate.correspondence": "Contact Negotiate Correspondence",
        "contact.negotiate.meet": "Contact Negotiate Meet",
        "contact.negotiate.n/a": "Contact Negotiate",
        "contact.prevarication.broadcast": "Contact Prevarication Broadcast",
        "contact.prevarication.correspondence": "Contact Prevarication Correspondence",
        "contact.prevarication.meet": "Contact Prevarication Meet",
        "contact.prevarication.n/a": "Contact Prevarication",
        "contact.publicstatementinperson.broadcast": "Contact Public Statement In Person Broadcast",
        "contact.publicstatementinperson.n/a": "Contact Public Statement In Person",
        "contact.requestadvise.broadcast": "Contact Request Advise Broadcast",
        "contact.requestadvise.correspondence": "Contact Request Advise Correspondence",
        "contact.requestadvise.meet": "Contact Request Advise Meet",
        "contact.requestadvise.n/a": "Contact Request Advise",
        "contact.threatencoerce.broadcast": "Contact Threaten Coerce Broadcast",
        "contact.threatencoerce.correspondence": "Contact Threaten Coerce Correspondence",
        "contact.threatencoerce.meet": "Contact Threaten Coerce Meet",
        "contact.threatencoerce.n/a": "Contact Threaten Coerce",
        "disaster.accidentcrash.accidentcrash": "Disaster Accidentcrash Accidentcrash",
        "disaster.fireexplosion.fireexplosion": "Disaster Fireexplosion Fireexplosion",
        "government.agreements.acceptagreementcontractceasefire": "Government Agreements Accept Agreement Contract Ceasefire",
        "government.agreements.n/a": "Government Agreements",
        "government.agreements.rejectnullifyagreementcontractceasefire": "Government Agreements Reject Nullify Agreement Contract Ceasefire",
        "government.agreements.violateagreement": "Government Agreements Violate Agreement",
        "government.formation.mergegpe": "Government Formation Mergegpe",
        "government.formation.n/a": "Government Formation",
        "government.formation.startgpe": "Government Formation Startpage",
        "government.legislate.legislate": "Government Legislate Legislate",
        "government.spy.spy": "Government Spy Spy",
        "government.vote.castvote": "Government Vote Castvote",
        "government.vote.n/a": "Government Vote",
        "government.vote.violationspreventvote": "Government Vote Violations Prevent Vote",
        "inspection.sensoryobserve.inspectpeopleorganization": "Inspection Sensory Observe Inspect People Organization",
        "inspection.sensoryobserve.monitorelection": "Inspection Sensory Observe Monitor Election",
        "inspection.sensoryobserve.n/a": "Inspection Sensory Observe",
        "inspection.sensoryobserve.physicalinvestigateinspect": "Inspection Sensory Observe Physical Investigate Inspect",
        "justice.arrestjaildetain.arrestjaildetain": "Justice Arrest Jail Detain",
        "justice.initiatejudicialprocess.chargeindict": "Justice Initiative Judicial Process Charge Indict",
        "justice.initiatejudicialprocess.n/a": "Justice Initiative Judicial Process",
        "justice.initiatejudicialprocess.trialhearing": "Justice Initiative Judicial Process Trial Hearing",
        "justice.investigate.investigatecrime": "Justice Investigate Investigate Crime",
        "justice.investigate.n/a": "Justice Investigate",
        "justice.judicialconsequences.convict": "Justice Judicial Consequences Convict",
        "justice.judicialconsequences.execute": "Justice Judicial Consequences Execute",
        "justice.judicialconsequences.extradite": "Justice Judicial Consequences Extradite",
        "justice.judicialconsequences.n/a": "Justice Judicial Consequences",
        "life.die.deathcausedbyviolentevents": "Life Die Death Caused By Violent Events",
        "life.die.n/a": "Life Die",
        "life.die.nonviolentdeath": "Life Die Non Violent Death",
        "life.injure.illnessdegradationhungerthirst": "Life Injure Illness Degradation Hunger Thirst",
        "life.injure.illnessdegradationphysical": "Life Injure Illness Degradation Physical",
        "life.injure.injurycausedbyviolentevents": "Life Injure Injury Caused By Violent Events",
        "life.injure.n/a": "Life Injure",
        "manufacture.artifact.build": "Manufacture Artifact Build",
        "manufacture.artifact.createintellectualproperty": "Manufacture Artifact Create Intellectual Property",
        "manufacture.artifact.createmanufacture": "Manufacture Artifact Create Manufacture",
        "manufacture.artifact.n/a": "Manufacture Artifact",
        "movement.transportartifact.bringcarryunload": "Movement Transport Artifact Bring Carry Unload",
        "movement.transportartifact.disperseseparate": "Movement Transport Artifact Disperse Separate",
        "movement.transportartifact.fall": "Movement Transport Artifact Fall",
        "movement.transportartifact.grantentry": "Movement Transport Artifact Grant Entry",
        "movement.transportartifact.hide": "Movement Transport Artifact Hide",
        "movement.transportartifact.n/a": "Movement Transport Artifact",
        "movement.transportartifact.nonviolentthrowlaunch": "Movement Transport Artifact Nonviolent Throw Launch",
        "movement.transportartifact.prevententry": "Movement Transport Artifact Prevent Entry",
        "movement.transportartifact.preventexit": "Movement Transport Artifact Prevent Exit",
        "movement.transportartifact.receiveimport": "Movement Transport Artifact Receive Import",
        "movement.transportartifact.sendsupplyexport": "Movement Transport Artifact Send Supply Export",
        "movement.transportartifact.smuggleextract": "Movement Transport Artifact Smuggle Extract",
        "movement.transportperson.bringcarryunload": "Movement Transport Person Bring Carry Unload",
        "movement.transportperson.disperseseparate": "Movement Transport Person Disperse Separate",
        "movement.transportperson.evacuationrescue": "Movement Transport Person Evacuation Rescue",
        "movement.transportperson.fall": "Movement Transport Person Fall",
        "movement.transportperson.grantentryasylum": "Movement Transport Person Grantentry Asylum",
        "movement.transportperson.hide": "Movement Transport Person Hide",
        "movement.transportperson.n/a": "Movement Transport Person",
        "movement.transportperson.prevententry": "Movement Transport Person Prevent Entry",
        "movement.transportperson.preventexit": "Movement Transport Person Prevent Exit",
        "movement.transportperson.selfmotion": "Movement Transport Person Self Motion",
        "movement.transportperson.smuggleextract": "Movement Transport Person Smuggle Extract",
        "personnel.elect.n/a": "Personnel Elect",
        "personnel.elect.winelection": "Personnel Elect Win Election",
        "personnel.endposition.firinglayoff": "Personnel End Position Firing Layoff",
        "personnel.endposition.n/a": "Personnel End Position",
        "personnel.endposition.quitretire": "Personnel End Position Quit Retire",
        "personnel.startposition.hiring": "Personnel Start Position Hiring",
        "personnel.startposition.n/a": "Personnel Start Position",
        "transaction.transaction.embargosanction": "Transaction Transaction Embargo Sanction",
        "transaction.transaction.giftgrantprovideaid": "Transaction Transaction Gift Grant Provide Aid",
        "transaction.transaction.n/a": "Transaction Transaction",
        "transaction.transaction.transfercontrol": "Transaction Transaction Transfer Control",
        "transaction.transfermoney.borrowlend": "Transaction Transfer Money Borrow Lend",
        "transaction.transfermoney.embargosanction": "Transaction Transfer Money Embargo Sanction",
        "transaction.transfermoney.giftgrantprovideaid": "Transaction Transfer Money Gift Grant Provide Aid",
        "transaction.transfermoney.n/a": "Transaction Transfer Money",
        "transaction.transfermoney.payforservice": "Transaction Transfer Money Payforservice",
        "transaction.transfermoney.purchase": "Transaction Transfer Money Purchase",
        "transaction.transferownership.borrowlend": "Transaction Transfer Ownership Borrow Lend",
        "transaction.transferownership.embargosanction": "Transaction Transfer Ownership Embargo Sanction",
        "transaction.transferownership.giftgrantprovideaid": "Transaction Transfer Ownership Gift Grant Provide Aid",
        "transaction.transferownership.n/a": "Transaction Transfer Ownership",
        "transaction.transferownership.purchase": "Transaction Transfer Ownership Purchase",  
    },
    "wikievents": {
        "ArtifactExistence.DamageDestroyDisableDismantle.Damage": "Artifact Existence Damage Destroy Disable Dismantle Damage",
        "ArtifactExistence.DamageDestroyDisableDismantle.Destroy": "Artifact Existence Damage Destroy Disable Dismantle Destroy",
        "ArtifactExistence.DamageDestroyDisableDismantle.DisableDefuse": "Artifact Existence Damage Destroy Disable Dismantle Disable Defuse",
        "ArtifactExistence.DamageDestroyDisableDismantle.Dismantle": "Artifact Existence Damage Destroy Disable Dismantle Dismantle",
        "ArtifactExistence.DamageDestroyDisableDismantle.Unspecified": "Artifact Existence Damage Destroy Disable Dismantle",
        "ArtifactExistence.ManufactureAssemble.Unspecified": "Artifact Existence Manufacture Assemble",
        "Cognitive.IdentifyCategorize.Unspecified": "Cognitive Identify Categorize",
        "Cognitive.Inspection.SensoryObserve": "Cognitive Inspection Sensory Observe",
        "Cognitive.Research.Unspecified": "Cognitive Research",
        "Cognitive.TeachingTrainingLearning.Unspecified": "Cognitive Teaching Training Learning",
        "Conflict.Attack.DetonateExplode": "Conflict Attack Detonate Explode",
        "Conflict.Attack.Unspecified": "Conflict Attack",
        "Conflict.Defeat.Unspecified": "Conflict Defeat",
        "Conflict.Demonstrate.DemonstrateWithViolence": "Conflict Demonstrate Demonstrate With Violence",
        "Conflict.Demonstrate.Unspecified": "Conflict Demonstrate",
        "Contact.Contact.Broadcast": "Contact Contact Broadcast",
        "Contact.Contact.Correspondence": "Contact Contact Correspondence",
        "Contact.Contact.Meet": "Contact Contact Meet",
        "Contact.Contact.Unspecified": "Contact Contact",
        "Contact.RequestCommand.Broadcast": "Contact Request Command Broadcast",
        "Contact.RequestCommand.Correspondence": "Contact Request Command Correspondence",
        "Contact.RequestCommand.Meet": "Contact Request Command Meet",
        "Contact.RequestCommand.Unspecified": "Contact Request Command",
        "Contact.ThreatenCoerce.Broadcast": "Contact Threaten Coerce Broadcast",
        "Contact.ThreatenCoerce.Correspondence": "Contact Threaten Coerce Correspondence",
        "Contact.ThreatenCoerce.Unspecified": "Contact Threaten Coerce",
        "Control.ImpedeInterfereWith.Unspecified": "Control Impede Interfere With",
        "Disaster.Crash.Unspecified": "Disaster Crash",
        "Disaster.DiseaseOutbreak.Unspecified": "Disaster Disease Outbreak",
        "GenericCrime.GenericCrime.GenericCrime": "Generic Crime Generic Crime Generic Crime",
        "Justice.Acquit.Unspecified": "Justice Acquit",
        "Justice.ArrestJailDetain.Unspecified": "Justice Arrest Jail Detain",
        "Justice.ChargeIndict.Unspecified": "Justice Charge Indict",
        "Justice.Convict.Unspecified": "Justice Convict",
        "Justice.InvestigateCrime.Unspecified": "Justice Investigate Crime",
        "Justice.ReleaseParole.Unspecified": "Justice Release Parole",
        "Justice.Sentence.Unspecified": "Justice Sentence",
        "Justice.TrialHearing.Unspecified": "Justice Trial Hearing",
        "Life.Die.Unspecified": "Life Die",
        "Life.Infect.Unspecified": "Life Infect",
        "Life.Injure.Unspecified": "Life Injure",
        "Medical.Intervention.Unspecified": "Medical Intervention",
        "Movement.Transportation.Evacuation": "Movement Transportation Evacuation",
        "Movement.Transportation.IllegalTransportation": "Movement Transportation Illegal Transportation",
        "Movement.Transportation.PreventPassage": "Movement Transportation Prevent Passage",
        "Movement.Transportation.Unspecified": "Movement Transportation",
        "Personnel.EndPosition.Unspecified": "Personnel End Position",
        "Personnel.StartPosition.Unspecified": "Personnel Start Position",
        "Transaction.Donation.Unspecified": "Transaction Donation",
        "Transaction.ExchangeBuySell.Unspecified": "Transaction Exchange Buy Sell",
    },
    "fewevent": {
        "Business.Collaboration": "Business Collaboration", 
        "Business.Declare-Bankruptcy": "Business Declare Bankruptcy", 
        "Business.Employment": "Business Employment", 
        "Business.Employment-Tenure": "Business Employment Tenure", 
        "Business.End-Org": "Business End Org", 
        "Business.Financing": "Business Financing", 
        "Business.Investment": "Business Investment", 
        "Business.Layoff": "Business Layoff", 
        "Business.Merge-Org": "Business Merge Org", 
        "Business.Sponsorship": "Business Sponsorship", 
        "Business.Start-Org": "Business Start Org", 
        "Business.Start-Subsidiary": "Business Start Subsidiary", 
        "Conflict.Attack": "Conflict Attack", 
        "Conflict.Demonstrate": "Conflict Demonstrate", 
        "Conflict.Riot": "Conflict Riot", 
        "Conflict.Self-Immolation": "Conflict Self Immolation", 
        "Contact.Broadcast": "Contact Broadcast", 
        "Contact.Contact": "Contact Contact", 
        "Contact.Correspondence": "Contact Correspondence", 
        "Contact.E-Mail": "Contact E Mail", 
        "Contact.Letter-Communication": "Contact Letter Communication", 
        "Contact.Meet": "Contact Meet", 
        "Contact.Online-Chat": "Contact Online Chat", 
        "Contact.Phone-Write": "Contact Phone Write", 
        "Contact.Video-Chat": "Contact Video Chat", 
        "Contact.Voice-Mail": "Contact Voice Mail", 
        "Education.Education": "Education Education", 
        "Film.Dubbing-Performance": "Film Dubbing Performance", 
        "Film.Film-Crew-Gig": "Film Film Crew Gig", 
        "Film.Film-Distribution": "Film Film Distribution", 
        "Film.Film-Festival": "Film Film Festival", 
        "Film.Film-Production": "Film Film Production", 
        "Justice.Acquit": "Justice Acquit", 
        "Justice.Appeal": "Justice Appeal", 
        "Justice.Arrest-Jail": "Justice Arrest Jail", 
        "Justice.Charge-Indict": "Justice Charge Indict", 
        "Justice.Convict": "Justice Convict", 
        "Justice.Execute": "Justice Execute", 
        "Justice.Extradite": "Justice Extradite", 
        "Justice.Fine": "Justice Fine", 
        "Justice.Pardon": "Justice Pardon", 
        "Justice.Release-Parole": "Justice Release Parole", 
        "Justice.Sentence": "Justice Sentence", 
        "Justice.Sue": "Justice Sue", 
        "Justice.Trial-Hearing": "Justice Trial Hearing", 
        "Life.Abortion": "Life Abortion", 
        "Life.Be-Born": "Life Be Born", 
        "Life.Die": "Life Die", 
        "Life.Divorce": "Life Divorce", 
        "Life.Homesick": "Life Homesick", 
        "Life.Injure": "Life Injure", 
        "Life.Marry": "Life Marry", 
        "Life.Pregnancy": "Life Pregnancy", 
        "Life.Sick": "Life Sick", 
        "Life.Travel": "Life Travel", 
        "Manufacture.Artifact": "Manufacture Artifact", 
        "Manufacture.Lean-Manufacturing": "Manufacture Lean Manufacturing", 
        "Military.Military-Command": "Military Military Command", 
        "Military.Military-Service": "Military Military Service", 
        "Military.Recruit-Training": "Military Recruit Training", 
        "Military.Recruitment": "Military Recruitment", 
        "Movement.Driving": "Movement Driving", 
        "Movement.Parking": "Movement Parking", 
        "Movement.Transport": "Movement Transport", 
        "Movement.Transport-Artifact": "Movement Transport Artifact", 
        "Movement.Transportperson": "Movement Transportperson", 
        "Music.Compose": "Music Compose", 
        "Music.Dance": "Music Dance", 
        "Music.Group-Membership": "Music Group Membership", 
        "Music.Sing": "Music Sing", 
        "Music.Track-Contribution": "Music Track Contribution", 
        "Olympics.Closing-Ceremony": "Olympics Closing Ceremony", 
        "Olympics.Olympic-Athlete-Affiliation": "Olympics Olympic Athlete Affiliation", 
        "Olympics.Olympic-Medal-Honor": "Olympics Olympic Medal Honor", 
        "Olympics.Opening-Ceremony": "Olympics Opening Ceremony", 
        "Organization.Division-Of-Labour": "Organization Division Of Labour", 
        "Organization.Leadership": "Organization Leadership", 
        "Organization.Org-Communication": "Organization Org Communication", 
        "Organization.Organization-Board-Membership": "Organization Organization Board Membership", 
        "People.Appointment": "People Appointment", 
        "People.Place-Lived": "People Place Lived", 
        "Personnel.Demotion": "Personnel Demotion", 
        "Personnel.Elect": "Personnel Elect", 
        "Personnel.End-Position": "Personnel End Position", 
        "Personnel.Nominate": "Personnel Nominate", 
        "Personnel.Performance-Appraisal": "Personnel Performance Appraisal", 
        "Personnel.Promotion": "Personnel Promotion", 
        "Personnel.Resignation": "Personnel Resignation", 
        "Personnel.Start-Position": "Personnel Start Position", 
        "Projects.Project-Participation": "Projects Project Participation", 
        "Sports.Fair-Play": "Sports Fair Play", 
        "Sports.Sports-Team-Roster": "Sports Sports Team Roster", 
        "Sports.Sports-Team-Season-Record": "Sports Sports Team Season Record", 
        "Sports.Tournament": "Sports Tournament", 
        "Transaction.Deposit": "Transaction Deposit", 
        "Transaction.Money-Laundering": "Transaction Money Laundering", 
        "Transaction.Transaction": "Transaction Transaction", 
        "Transaction.Transfer-Money": "Transaction Transfer Money", 
        "Transaction.Transfer-Ownership": "Transaction Transfer Ownership", 
        "Wine.Grape-Variety-Composition": "Wine Grape Variety Composition", 
    },
    "phee": {
        "Adverse_event": "Adverse Event",
        "Potential_therapeutic_event": "Potential Therapeutic Event", 
    },
    "casie": {
        "Attack:Databreach": "Attack Databreach",
        "Attack:Phishing": "Attack Phishing",
        "Attack:Ransom": "Attack Ransom",
        "Vulnerability-related:DiscoverVulnerability": "Vulnerability-Related Discover Vulnerability",
        "Vulnerability-related:PatchVulnerability": "Vulnerability-Related Patch Vulnerability",
    },
    "mlee": {
        "Acetylation": "Acetylation",
        "Binding": "Binding",
        "Blood_vessel_development": "Blood Vessel Development",
        "Breakdown": "Breakdown",
        "Catabolism": "Catabolism",
        "Cell_division": "Cell Division",
        "Cell_proliferation": "Cell Proliferation",
        "DNA_methylation": "DNA Methylation",
        "Death": "Death",
        "Dephosphorylation": "Dephosphorylation",
        "Development": "Development",
        "Dissociation": "Dissociation",
        "Gene_expression": "Gene Expression",
        "Growth": "Growth",
        "Localization": "Localization",
        "Metabolism": "Metabolism",
        "Negative_regulation": "Negative Regulation",
        "Pathway": "Pathway",
        "Phosphorylation": "Phosphorylation",
        "Planned_process": "Planned Process",
        "Positive_regulation": "Positive Regulation",
        "Protein_processing": "Protein Processing",
        "Regulation": "Regulation",
        "Remodeling": "Remodeling",
        "Reproduction": "Reproduction",
        "Synthesis": "Synthesis",
        "Transcription": "Transcription",
        "Translation": "Translation",
        "Ubiquitination": "Ubiquitination",
    }, 
    "genia2011": {
        "Binding": "Binding",
        "Gene_expression": "Gene Expression",
        "Localization": "Localization",
        "Negative_regulation": "Negative Regulation",
        "Phosphorylation": "Phosphorylation",
        "Positive_regulation": "Positive Regulation",
        "Protein_catabolism": "Protein Catabolism",
        "Regulation": "Regulation",
        "Transcription": "Transcription",
    },
    "genia2013": {
        "Acetylation": "Acetylation",
        "Binding": "Binding",
        "Deacetylation": "Deacetylation",
        "Gene_expression": "Gene Expression",
        "Localization": "Localization",
        "Negative_regulation": "Negative Regulation",
        "Phosphorylation": "Phosphorylation",
        "Positive_regulation": "Positive Regulation",
        "Protein_catabolism": "Protein Catabolism",
        "Protein_modification": "Protein Modification",
        "Regulation": "Regulation",
        "Transcription": "Transcription",
        "Ubiquitination": "Ubiquitination",
    },
    "speed": {
        "control": "Control", 
        "cure": "Cure", 
        "death": "Death", 
        "infect": "Infect", 
        "prevent": "Prevent", 
        "spread": "Spread", 
        "symptom": "Symptom", 
    }, 
}
